/*
 * Copyright (c) 2011, The DART development contributors
 * All rights reserved.
 *
 * The list of contributors can be found at:
 *   https://github.com/dartsim/dart/blob/main/LICENSE
 *
 * This file is provided under the following "BSD-style" License:
 *   Redistribution and use in source and binary forms, with or
 *   without modification, are permitted provided that the following
 *   conditions are met:
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
 *   CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 *   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 *   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *   DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 *   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 *   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 *   AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *   LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *   ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *   POSSIBILITY OF SUCH DAMAGE.
 */

#include <dart/simulation/experimental/common/exceptions.hpp>
#include <dart/simulation/experimental/multibody/multibody.hpp>
#include <dart/simulation/experimental/world.hpp>

#include <Eigen/Core>
#include <gtest/gtest.h>

#include <limits>
#include <string>
#include <vector>

// Test Multibody creation with explicit name
TEST(Multibody, CreationWithName)
{
  dart::simulation::experimental::World world;
  auto mb = world.addMultibody("multibody");

  EXPECT_EQ(mb.getName(), "multibody");
  EXPECT_EQ(mb.getLinkCount(), 0u);
  EXPECT_EQ(mb.getJointCount(), 0u);
  EXPECT_EQ(mb.getDOFCount(), 0u);
}

// Test Multibody creation with auto-generated name
TEST(Multibody, AutoGeneratedName)
{
  dart::simulation::experimental::World world;

  auto mb1 = world.addMultibody("");
  auto mb2 = world.addMultibody("");

  EXPECT_EQ(mb1.getName(), "multibody_001");
  EXPECT_EQ(mb2.getName(), "multibody_002");
}

// Test mixed explicit and auto-generated names
TEST(Multibody, MixedNamesRejectDuplicates)
{
  namespace sim = dart::simulation::experimental;

  sim::World world;

  auto mb1 = world.addMultibody("robot"); // Explicit
  auto mb2 = world.addMultibody("");      // Auto: "multibody_001"
  EXPECT_THROW(world.addMultibody("robot"), sim::InvalidArgumentException);
  EXPECT_THROW(
      world.addMultibody("multibody_001"), sim::InvalidArgumentException);
  auto mb4 = world.addMultibody(""); // Auto: "multibody_002"

  EXPECT_EQ(mb1.getName(), "robot");
  EXPECT_EQ(mb2.getName(), "multibody_001");
  EXPECT_EQ(mb4.getName(), "multibody_002");

  sim::World worldWithExplicitGeneratedName;
  [[maybe_unused]] auto explicitName
      = worldWithExplicitGeneratedName.addMultibody("multibody_001");
  auto generated = worldWithExplicitGeneratedName.addMultibody("");
  EXPECT_EQ(generated.getName(), "multibody_002");
}

// Test Multibody creation with different names
TEST(Multibody, CustomNames)
{
  dart::simulation::experimental::World world;

  auto robot = world.addMultibody("ur5");
  EXPECT_EQ(robot.getName(), "ur5");

  auto character = world.addMultibody("humanoid");
  EXPECT_EQ(character.getName(), "humanoid");

  auto mechanism = world.addMultibody("cabinet");
  EXPECT_EQ(mechanism.getName(), "cabinet");
}

// Test Multibody name get/set
TEST(Multibody, NameGetSet)
{
  namespace sim = dart::simulation::experimental;

  sim::World world;
  auto mb = world.addMultibody("initial_name");
  [[maybe_unused]] auto other = world.addMultibody("other");
  EXPECT_EQ(mb.getName(), "initial_name");

  mb.setName("new_name");
  EXPECT_EQ(mb.getName(), "new_name");

  mb.setName("robot_arm");
  EXPECT_EQ(mb.getName(), "robot_arm");

  EXPECT_THROW(mb.setName(""), sim::InvalidArgumentException);
  EXPECT_THROW(mb.setName("other"), sim::InvalidArgumentException);
  EXPECT_EQ(mb.getName(), "robot_arm");
}

// Links cannot be reparented via Frame API
TEST(Multibody, LinkReparentThrows)
{
  dart::simulation::experimental::World world;
  auto robot = world.addMultibody("robot");
  auto base = robot.addLink("base");
  auto child
      = robot.addLink("child", {.parentLink = base, .jointName = "joint"});

  EXPECT_THROW(
      child.setParentFrame(base),
      dart::simulation::experimental::InvalidOperationException);
}

// Test Multibody counts (currently empty)
TEST(Multibody, EmptyCounts)
{
  dart::simulation::experimental::World world;
  auto mb = world.addMultibody("test");

  // Empty multibody has no links, joints, or DOFs
  EXPECT_EQ(mb.getLinkCount(), 0u);
  EXPECT_EQ(mb.getJointCount(), 0u);
  EXPECT_EQ(mb.getDOFCount(), 0u);
}

// Test multiple Multibody instances in same World
TEST(Multibody, MultipleInstances)
{
  dart::simulation::experimental::World world;

  auto mb1 = world.addMultibody("multibody1");
  auto mb2 = world.addMultibody("multibody2");

  EXPECT_EQ(mb1.getName(), "multibody1");
  EXPECT_EQ(mb2.getName(), "multibody2");

  // Handles are independent
  mb1.setName("renamed1");
  EXPECT_EQ(mb1.getName(), "renamed1");
  EXPECT_EQ(mb2.getName(), "multibody2"); // Unchanged
}

//==============================================================================
// Joint and Link API Tests
//==============================================================================

// Test creating a single link (root link)
TEST(Multibody, CreateRootLink)
{
  dart::simulation::experimental::World world;
  auto robot = world.addMultibody("robot");

  // Create root link (no parent joint)
  robot.addLink("base");

  EXPECT_EQ(robot.getLinkCount(), 1u);
  EXPECT_EQ(robot.getJointCount(), 0u);
}

// Test creating a simple 2-link chain with revolute joint
TEST(Multibody, SimpleTwoLinkChain)
{
  dart::simulation::experimental::World world;
  auto robot = world.addMultibody("robot");

  // Create kinematic chain: base -> joint1 -> link1
  auto baseLink = robot.addLink("base");
  robot.addLink(
      "link1",
      {.parentLink = baseLink,
       .jointName = "joint1",
       .jointType = dart::simulation::experimental::JointType::Revolute});

  EXPECT_EQ(robot.getLinkCount(), 2u);
  EXPECT_EQ(robot.getJointCount(), 1u);
}

// Test creating a link with the shared JointSpec construction value object
TEST(Multibody, JointSpecConstruction)
{
  namespace sim = dart::simulation::experimental;

  sim::World world;
  auto robot = world.addMultibody("robot");
  auto base = robot.addLink("base");

  auto child = robot.addLink(
      "forearm",
      base,
      sim::JointSpec{
          .name = "elbow",
          .type = sim::JointType::Revolute,
          .axis = Eigen::Vector3d::UnitY()});

  auto joint = child.getParentJoint();
  EXPECT_TRUE(joint.isValid());
  EXPECT_EQ(joint.getName(), "elbow");
  EXPECT_EQ(joint.getType(), sim::JointType::Revolute);
  EXPECT_TRUE(joint.getAxis().isApprox(Eigen::Vector3d::UnitY()));
  EXPECT_EQ(robot.getLinkCount(), 2u);
  EXPECT_EQ(robot.getJointCount(), 1u);
  EXPECT_EQ(robot.getDOFCount(), 1u);
}

TEST(Multibody, EnumeratesLinksAndJointsInConstructionOrder)
{
  namespace sim = dart::simulation::experimental;

  sim::World world;
  auto robot = world.addMultibody("robot");
  auto base = robot.addLink("base");
  auto forearm = robot.addLink(
      "forearm",
      base,
      sim::JointSpec{
          .name = "elbow",
          .type = sim::JointType::Revolute,
          .axis = Eigen::Vector3d::UnitZ()});
  robot.addLink(
      "tool",
      forearm,
      sim::JointSpec{
          .name = "wrist",
          .type = sim::JointType::Revolute,
          .axis = Eigen::Vector3d::UnitY()});

  const auto links = robot.getLinks();
  ASSERT_EQ(links.size(), 3u);
  EXPECT_EQ(links[0].getName(), "base");
  EXPECT_EQ(links[1].getName(), "forearm");
  EXPECT_EQ(links[2].getName(), "tool");
  EXPECT_EQ(
      robot.getLinkNames(),
      (std::vector<std::string>{"base", "forearm", "tool"}));

  const auto joints = robot.getJoints();
  ASSERT_EQ(joints.size(), 2u);
  EXPECT_EQ(joints[0].getName(), "elbow");
  EXPECT_EQ(joints[0].getChildLink().getName(), "forearm");
  EXPECT_EQ(joints[1].getName(), "wrist");
  EXPECT_EQ(joints[1].getChildLink().getName(), "tool");
  EXPECT_EQ(
      robot.getJointNames(), (std::vector<std::string>{"elbow", "wrist"}));
}

TEST(Multibody, RejectsDuplicateLinkAndJointNames)
{
  namespace sim = dart::simulation::experimental;

  sim::World world;
  auto robot = world.addMultibody("robot");
  auto base = robot.addLink("base");

  EXPECT_THROW(robot.addLink("base"), sim::InvalidArgumentException);
  EXPECT_EQ(robot.getLinkCount(), 1u);
  EXPECT_EQ(robot.getJointCount(), 0u);

  auto forearm = robot.addLink(
      "forearm",
      base,
      sim::JointSpec{
          .name = "elbow",
          .type = sim::JointType::Revolute,
          .axis = Eigen::Vector3d::UnitZ()});

  EXPECT_THROW(
      robot.addLink(
          "forearm",
          base,
          sim::JointSpec{
              .name = "wrist",
              .type = sim::JointType::Revolute,
              .axis = Eigen::Vector3d::UnitY()}),
      sim::InvalidArgumentException);
  EXPECT_EQ(robot.getLinkCount(), 2u);
  EXPECT_EQ(robot.getJointCount(), 1u);
  EXPECT_THROW(
      robot.addLink(
          "tool",
          forearm,
          sim::JointSpec{
              .name = "elbow",
              .type = sim::JointType::Revolute,
              .axis = Eigen::Vector3d::UnitY()}),
      sim::InvalidArgumentException);
  EXPECT_EQ(robot.getLinkCount(), 2u);
  EXPECT_EQ(robot.getJointCount(), 1u);
}

TEST(Multibody, LinkAndJointNamesAreLocalToMultibody)
{
  namespace sim = dart::simulation::experimental;

  sim::World world;
  auto robot1 = world.addMultibody("robot1");
  auto base1 = robot1.addLink("base");
  robot1.addLink(
      "link",
      base1,
      sim::JointSpec{
          .name = "joint",
          .type = sim::JointType::Revolute,
          .axis = Eigen::Vector3d::UnitZ()});

  auto robot2 = world.addMultibody("robot2");
  auto base2 = robot2.addLink("base");
  robot2.addLink(
      "link",
      base2,
      sim::JointSpec{
          .name = "joint",
          .type = sim::JointType::Revolute,
          .axis = Eigen::Vector3d::UnitZ()});

  EXPECT_EQ(robot1.getLinkNames(), (std::vector<std::string>{"base", "link"}));
  EXPECT_EQ(robot2.getLinkNames(), (std::vector<std::string>{"base", "link"}));
  EXPECT_EQ(robot1.getJointNames(), (std::vector<std::string>{"joint"}));
  EXPECT_EQ(robot2.getJointNames(), (std::vector<std::string>{"joint"}));
}

TEST(Multibody, AutoNamesSkipExistingLinkAndJointNames)
{
  namespace sim = dart::simulation::experimental;

  sim::World world;
  auto robot = world.addMultibody("robot");
  [[maybe_unused]] auto explicitAutoName = robot.addLink("link_001");

  auto base = robot.addLink("");
  EXPECT_EQ(base.getName(), "link_002");

  auto forearm = robot.addLink(
      "forearm",
      base,
      sim::JointSpec{
          .name = "joint_001",
          .type = sim::JointType::Revolute,
          .axis = Eigen::Vector3d::UnitZ()});
  auto tool = robot.addLink(
      "tool",
      forearm,
      sim::JointSpec{
          .name = "",
          .type = sim::JointType::Revolute,
          .axis = Eigen::Vector3d::UnitY()});

  EXPECT_EQ(forearm.getParentJoint().getName(), "joint_001");
  EXPECT_EQ(tool.getParentJoint().getName(), "joint_002");
}

TEST(Multibody, RejectsInvalidJointSpecAxis)
{
  namespace sim = dart::simulation::experimental;

  sim::World world;
  auto robot = world.addMultibody("robot");
  auto base = robot.addLink("base");

  EXPECT_THROW(
      robot.addLink(
          "zero_axis",
          base,
          sim::JointSpec{
              .name = "zero_axis_joint",
              .type = sim::JointType::Revolute,
              .axis = Eigen::Vector3d::Zero()}),
      sim::InvalidArgumentException);

  EXPECT_THROW(
      robot.addLink(
          "nan_axis",
          base,
          sim::JointSpec{
              .name = "nan_axis_joint",
              .type = sim::JointType::Revolute,
              .axis = Eigen::Vector3d(
                  std::numeric_limits<double>::quiet_NaN(), 0.0, 0.0)}),
      sim::InvalidArgumentException);
}

TEST(Multibody, RejectsDegeneratePlanarOrUniversalJointAxis)
{
  namespace sim = dart::simulation::experimental;

  sim::World world;
  auto robot = world.addMultibody("robot");
  auto base = robot.addLink("base");

  // A planar joint whose normal axis is parallel to the default in-plane axis2
  // (UnitX) collapses the in-plane basis, so it must be rejected.
  EXPECT_THROW(
      robot.addLink(
          "degenerate_planar",
          base,
          sim::JointSpec{
              .name = "degenerate_planar_joint",
              .type = sim::JointType::Planar,
              .axis = Eigen::Vector3d::UnitX()}),
      sim::InvalidArgumentException);

  // A universal joint with both rotation axes parallel is likewise degenerate.
  EXPECT_THROW(
      robot.addLink(
          "degenerate_universal",
          base,
          sim::JointSpec{
              .name = "degenerate_universal_joint",
              .type = sim::JointType::Universal,
              .axis = Eigen::Vector3d::UnitX()}),
      sim::InvalidArgumentException);

  // A planar joint whose normal axis is not parallel to axis2 is valid.
  EXPECT_NO_THROW(robot.addLink(
      "valid_planar",
      base,
      sim::JointSpec{
          .name = "valid_planar_joint",
          .type = sim::JointType::Planar,
          .axis = Eigen::Vector3d::UnitZ()}));
}

// A link's local transform must include the parent joint motion so that it
// matches the parent-relative transform and the world-transform identity holds.
TEST(Multibody, LinkLocalTransformIncludesJointMotion)
{
  namespace sim = dart::simulation::experimental;

  sim::World world;
  auto robot = world.addMultibody("robot");
  auto base = robot.addLink("base");
  auto link1 = robot.addLink(
      "link1",
      base,
      sim::JointSpec{
          .name = "joint1",
          .type = sim::JointType::Revolute,
          .axis = Eigen::Vector3d::UnitZ()});

  world.enterSimulationMode();

  auto joint = link1.getParentJoint();
  joint.setPosition(Eigen::VectorXd::Constant(1, 0.5));
  world.updateKinematics();

  const Eigen::Isometry3d local = link1.getLocalTransform();
  const Eigen::Isometry3d relativeToParent = link1.getTransform(base);

  // local_transform equals relative_transform(parent) and reflects joint
  // motion.
  EXPECT_TRUE(local.isApprox(relativeToParent));
  EXPECT_FALSE(local.isApprox(Eigen::Isometry3d::Identity()));

  // worldTransform == parent.getTransform() * getLocalTransform().
  EXPECT_TRUE(link1.getTransform().isApprox(base.getTransform() * local));
}

// Test creating a serial manipulator (typical robot arm)
TEST(Multibody, SerialManipulator)
{
  dart::simulation::experimental::World world;
  auto robot = world.addMultibody("ur5");

  // Create 6-DOF serial manipulator: base -> 6 revolute joints -> 6 links
  auto base = robot.addLink("base");
  auto link1 = robot.addLink(
      "link1", {.parentLink = base, .jointName = "shoulder_pan"});
  auto link2 = robot.addLink(
      "link2", {.parentLink = link1, .jointName = "shoulder_lift"});
  auto link3
      = robot.addLink("link3", {.parentLink = link2, .jointName = "elbow"});
  auto link4
      = robot.addLink("link4", {.parentLink = link3, .jointName = "wrist1"});
  auto link5
      = robot.addLink("link5", {.parentLink = link4, .jointName = "wrist2"});
  robot.addLink("link6", {.parentLink = link5, .jointName = "wrist3"});

  EXPECT_EQ(robot.getLinkCount(), 7u);  // base + 6 links
  EXPECT_EQ(robot.getJointCount(), 6u); // 6 revolute joints
}

// Test creating prismatic joints
TEST(Multibody, PrismaticJoints)
{
  dart::simulation::experimental::World world;
  auto robot = world.addMultibody("linear_stage");

  // Create 3-DOF Cartesian robot (XYZ linear stages)
  auto base = robot.addLink("base");
  auto linkX = robot.addLink(
      "link_x",
      {.parentLink = base,
       .jointName = "joint_x",
       .jointType = dart::simulation::experimental::JointType::Prismatic,
       .axis = Eigen::Vector3d::UnitX()});
  auto linkY = robot.addLink(
      "link_y",
      {.parentLink = linkX,
       .jointName = "joint_y",
       .jointType = dart::simulation::experimental::JointType::Prismatic,
       .axis = Eigen::Vector3d::UnitY()});
  robot.addLink(
      "link_z",
      {.parentLink = linkY,
       .jointName = "joint_z",
       .jointType = dart::simulation::experimental::JointType::Prismatic,
       .axis = Eigen::Vector3d::UnitZ()});

  EXPECT_EQ(robot.getLinkCount(), 4u);
  EXPECT_EQ(robot.getJointCount(), 3u);
}

// Test mixing revolute and prismatic joints
TEST(Multibody, MixedJointTypes)
{
  dart::simulation::experimental::World world;
  auto robot = world.addMultibody("scara");

  // Create SCARA robot: 2 revolute + 1 prismatic + 1 revolute
  auto base = robot.addLink("base");
  auto link1 = robot.addLink(
      "link1",
      {.parentLink = base,
       .jointName = "joint1",
       .axis = Eigen::Vector3d::UnitZ()});
  auto link2 = robot.addLink(
      "link2",
      {.parentLink = link1,
       .jointName = "joint2",
       .axis = Eigen::Vector3d::UnitZ()});
  auto link3 = robot.addLink(
      "link3",
      {.parentLink = link2,
       .jointName = "joint3",
       .jointType = dart::simulation::experimental::JointType::Prismatic,
       .axis = Eigen::Vector3d::UnitZ()});
  robot.addLink(
      "link4",
      {.parentLink = link3,
       .jointName = "joint4",
       .axis = Eigen::Vector3d::UnitZ()});

  EXPECT_EQ(robot.getLinkCount(), 5u);
  EXPECT_EQ(robot.getJointCount(), 4u);
}

// Test custom joint axes
TEST(Multibody, CustomJointAxes)
{
  dart::simulation::experimental::World world;
  auto robot = world.addMultibody("custom_axes");

  auto base = robot.addLink("base");

  // Joint rotating around custom axis
  Eigen::Vector3d customAxis(1.0, 1.0, 0.0);
  auto link1 = robot.addLink(
      "link1", {.parentLink = base, .jointName = "joint1", .axis = customAxis});

  // Joint translating along custom direction
  Eigen::Vector3d customDir(0.0, 1.0, 1.0);
  robot.addLink(
      "link2",
      {.parentLink = link1,
       .jointName = "joint2",
       .jointType = dart::simulation::experimental::JointType::Prismatic,
       .axis = customDir});

  EXPECT_EQ(robot.getLinkCount(), 3u);
  EXPECT_EQ(robot.getJointCount(), 2u);
}

// Test design-time restriction: cannot add joints after entering simulation
// mode
TEST(Multibody, DesignTimeRestriction)
{
  dart::simulation::experimental::World world;
  auto robot = world.addMultibody("robot");

  // Create links in design mode
  auto base = robot.addLink("base");
  robot.addLink("link1", {.parentLink = base, .jointName = "joint1"});

  EXPECT_EQ(robot.getLinkCount(), 2u);
  EXPECT_EQ(robot.getJointCount(), 1u);

  // Enter simulation mode
  world.enterSimulationMode();
  EXPECT_TRUE(world.isSimulationMode());

  // Attempting to create link should throw
  EXPECT_THROW(
      robot.addLink("link2"),
      dart::simulation::experimental::InvalidArgumentException);
}

TEST(Multibody, RejectsParentLinkFromDifferentMultibody)
{
  namespace sim = dart::simulation::experimental;

  sim::World world;
  auto robot = world.addMultibody("robot");
  auto other = world.addMultibody("other");
  auto foreignBase = other.addLink("foreign_base");

  EXPECT_THROW(
      robot.addLink(
          "child",
          foreignBase,
          sim::JointSpec{
              .name = "joint",
              .type = sim::JointType::Revolute,
              .axis = Eigen::Vector3d::UnitZ()}),
      sim::InvalidArgumentException);
}

// Test branching kinematic tree (not just serial chain)
TEST(Multibody, BranchingKinematicTree)
{
  dart::simulation::experimental::World world;
  auto robot = world.addMultibody("humanoid");

  // Create simplified humanoid structure with branching
  auto torso = robot.addLink("torso");

  // Left arm branch
  auto leftShoulder = robot.addLink(
      "left_shoulder",
      {.parentLink = torso, .jointName = "left_shoulder_joint"});
  robot.addLink(
      "left_elbow",
      {.parentLink = leftShoulder, .jointName = "left_elbow_joint"});

  // Right arm branch
  auto rightShoulder = robot.addLink(
      "right_shoulder",
      {.parentLink = torso, .jointName = "right_shoulder_joint"});
  robot.addLink(
      "right_elbow",
      {.parentLink = rightShoulder, .jointName = "right_elbow_joint"});

  // Head branch
  auto neck
      = robot.addLink("neck", {.parentLink = torso, .jointName = "neck_joint"});
  robot.addLink("head", {.parentLink = neck, .jointName = "head_joint"});

  EXPECT_EQ(
      robot.getLinkCount(), 7u); // torso + 2 shoulders + 2 elbows + neck + head
  EXPECT_EQ(robot.getJointCount(), 6u); // 6 revolute joints
}

// Test that links persist across Multibody handle copies
TEST(Multibody, LinksPersistAcrossHandles)
{
  dart::simulation::experimental::World world;
  auto robot1 = world.addMultibody("robot");

  // Create links via robot1
  auto base = robot1.addLink("base");
  robot1.addLink("link1", {.parentLink = base, .jointName = "joint1"});

  // Get another handle to the same Multibody
  auto robot2 = world.getMultibody("robot");
  ASSERT_TRUE(robot2.has_value());

  // Both handles see the same links/joints
  EXPECT_EQ(robot1.getLinkCount(), 2u);
  EXPECT_EQ(robot2->getLinkCount(), 2u);
  EXPECT_EQ(robot1.getJointCount(), 1u);
  EXPECT_EQ(robot2->getJointCount(), 1u);
}
