# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 28

# Number of days of inactivity before a stale Issue or Pull Request is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: false

# Issues with these labels will never be considered stale
exemptLabels:
  - 'status: blocked'
  - 'status: help wanted'
  - 'status: in-progress'
  - 'status: on hold'

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false

# Limit the number of actions per hour, from 1-30. Default is 30.
# Set to 1 to prevent unintended spamming.
limitPerRun: 1

# Limit to only `issues` or `pulls`
only: issues
