brew 'git'
brew 'cmake'
brew 'assimp'
brew 'fcl'
brew 'bullet', args: ['--with-double-precision']
brew 'ode', args: ['--with-libccd', '--with-double-precision']
brew 'flann'
brew 'boost'
brew 'eigen'
brew 'tinyxml'
brew 'tinyxml2'
brew 'libccd'
brew 'nlopt'
#brew 'ipopt'
brew 'urdfdom'
brew 'open-scene-graph'
