# This file is automatically generated from CMake
# Include this file in CMakeLists.txt with 
# INCLUDE(${CMAKE_INSTALL_PREFIX}/share/dart/DART_config.cmake) 


INCLUDE_DIRECTORIES(/usr/local/include)
INCLUDE_DIRECTORIES(/usr/local/include/dart)
INCLUDE_DIRECTORIES(/usr/local/include/eigen-3.0.5)
INCLUDE_DIRECTORIES(/usr/local/include/fcl)
SET(DART_HEADERS /usr/local/include/dart /usr/local/include)

LINK_DIRECTORIES(/usr/local/lib)
SET(DART_LIBRARIES optimized collision optimized dynamics optimized geometry optimized kinematics optimized planning optimized renderer optimized utils debug collisiond debug dynamicsd debug geometryd debug kinematicsd debug planningd debug rendererd debug utilsd)

