FUNCTION(LINK_THIRDPARTY project extpj base)
  IF (WIN32)
    TARGET_LINK_LIBRARIES(${project} debug ${base}_d optimized ${base})
  ELSE()
    TARGET_LINK_LIBRARIES(${project} ${extpj})
  ENDIF()
ENDFUNCTION(LINK_THIRDPARTY)

FUNCTION(LINK_THIRDPARTY_EXT project extpj base)
  LINK_THIRDPARTY(${project} ${extpj} ${base})
  ADD_DEPENDENCIES(${project} ${extpj}-ext)
ENDFUNCTION(LINK_THIRDPARTY_EXT)

FUNCTION(LINK_THIRDPARTY_FREE_IMAGE project)
  LINK_THIRDPARTY_EXT(${project} freeimage libFreeImage)
ENDFUNCTION(LINK_THIRDPARTY_FREE_IMAGE)

FUNCTION(LINK_THIRDPARTY_GFLAGS project)
  LINK_THIRDPARTY_EXT(${project} gflags libgflags)
ENDFUNCTION(LINK_THIRDPARTY_GFLAGS)

FUNCTION(LINK_THIRDPARTY_GLOG project)
  LINK_THIRDPARTY_EXT(${project} glog libglog)
ENDFUNCTION(LINK_THIRDPARTY_GLOG)

FUNCTION(LINK_THIRDPARTY_GLUT project)
  TARGET_LINK_LIBRARIES(${project} ${OPENGL_LIBRARIES} ${GLUT_glut_LIBRARY})
ENDFUNCTION(LINK_THIRDPARTY_GLUT)

FUNCTION(LINK_THIRDPARTY_GTEST project)
  LINK_THIRDPARTY(${project} gtest libgtest)
  ADD_DEPENDENCIES(${project} gtest)
ENDFUNCTION(LINK_THIRDPARTY_GTEST)

FUNCTION(LINK_THIRDPARTY_GTEST_MAIN project)
  LINK_THIRDPARTY(${project} gtest_main libgtest_main)
  ADD_DEPENDENCIES(${project} gtest_main)
ENDFUNCTION(LINK_THIRDPARTY_GTEST_MAIN)

FUNCTION(LINK_THIRDPARTY_TICPP project)
  LINK_THIRDPARTY_EXT(${project} ticpp libticpp)
ENDFUNCTION(LINK_THIRDPARTY_TICPP)


