ARG BASE_IMAGE=quay.io/pypa/manylinux_2_28_x86_64
FROM $BASE_IMAGE

ARG NUM_CORES=8

# Missing optional dependencies:
#   ipopt
#   nlopt
#   spdlog

RUN yum install -y \
    boost-devel \
    glew-devel \
    freeglut-devel \
    python3-devel

# fmt
RUN git clone https://github.com/fmtlib/fmt.git -b '11.1.3' \
    && mkdir -p fmt/build \
    && cmake fmt -B fmt/build \
    -DCMAKE_BUILD_TYPE=Release \
    -DFMT_TEST=OFF \
    -DCMAKE_C_FLAGS="-fPIC" \
    -DCMAKE_CXX_FLAGS="-fPIC" \
    && cmake --build fmt/build --target install -j${NUM_CORES} \
    && rm -rf fmt

# assimp
RUN git clone https://github.com/assimp/assimp.git -b 'v5.4.3' \
    && mkdir -p assimp/build \
    && cmake assimp -B assimp/build -DCMAKE_BUILD_TYPE=Release -DASSIMP_BUILD_TESTS=OFF -DASSIMP_WARNINGS_AS_ERRORS=OFF \
    && cmake --build assimp/build --target install -j${NUM_CORES} \
    && rm -rf assimp

# eigen
RUN git clone https://gitlab.com/libeigen/eigen.git -b '3.4.0' \
    && mkdir -p eigen/build \
    && cmake eigen -B eigen/build -DCMAKE_BUILD_TYPE=Release -DEIGEN_BUILD_TESTING=OFF -DEIGEN_BUILD_DOC=OFF \
    && cmake --build eigen/build --target install -j${NUM_CORES} \
    && rm -rf eigen

# octomap
RUN git clone https://github.com/OctoMap/octomap.git -b 'v1.10.0' \
    && mkdir -p octomap/build \
    && cmake octomap -B octomap/build -DCMAKE_BUILD_TYPE=Release -DBUILD_OCTOVIS_SUBPROJECT=OFF -DBUILD_OCTOVIS_SUBPROJECT=OFF -DBUILD_DYNAMICETD3D_SUBPROJECT=OFF -DBUILD_TESTING=OFF \
    && cmake --build octomap/build --target install -j${NUM_CORES} \
    && rm -rf octomap

# libccd
RUN git clone https://github.com/danfis/libccd.git -b 'v2.1' \
    && mkdir -p libccd/build \
    && cmake libccd -B libccd/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF \
    && cmake --build libccd/build --target install -j${NUM_CORES} \
    && rm -rf libccd

# fcl
RUN git clone https://github.com/flexible-collision-library/fcl.git -b '0.7.0' \
    && mkdir -p fcl/build \
    && cmake fcl -B fcl/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF \
    && cmake --build fcl/build --target install -j${NUM_CORES} \
    && rm -rf fcl

# tinyxml2
RUN git clone https://github.com/leethomason/tinyxml2.git -b '10.0.0' \
    && mkdir -p tinyxml2/build \
    && cmake tinyxml2 -B tinyxml2/build -DCMAKE_BUILD_TYPE=Release -Dtinyxml2_BUILD_TESTING=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    && cmake --build tinyxml2/build --target install -j${NUM_CORES} \
    && rm -rf tinyxml2

# console_bridge
RUN git clone https://github.com/ros/console_bridge.git -b '1.0.2' \
    && mkdir -p console_bridge/build \
    && cmake console_bridge -B console_bridge/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF \
    && cmake --build console_bridge/build --target install -j${NUM_CORES} \
    && rm -rf console_bridge

# urdfdom_headers
RUN git clone https://github.com/ros/urdfdom_headers.git -b '1.1.1' \
    && mkdir -p urdfdom_headers/build \
    && cmake urdfdom_headers -B urdfdom_headers/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF \
    && cmake --build urdfdom_headers/build --target install -j${NUM_CORES} \
    && rm -rf urdfdom_headers

# urdfdom
RUN git clone https://github.com/ros/urdfdom.git -b '4.0.0' \
    && mkdir -p urdfdom/build \
    && cmake urdfdom -B urdfdom/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF \
    && cmake --build urdfdom/build --target install -j${NUM_CORES} \
    && rm -rf urdfdom

# Bullet
RUN git clone https://github.com/bulletphysics/bullet3.git -b '3.25' \
    && mkdir -p bullet3/build \
    && cmake bullet3 \
    -B bullet3/build \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_UNIT_TESTS=OFF \
    -DBUILD_CPU_DEMOS=OFF \
    -DBUILD_BULLET2_DEMOS=OFF \
    -DCMAKE_C_FLAGS="-fPIC" \
    -DCMAKE_CXX_FLAGS="-fPIC" \
    && cmake --build bullet3/build --target install -j${NUM_CORES} \
    && rm -rf bullet3

# openscenegraph
RUN git clone https://github.com/openscenegraph/OpenSceneGraph.git \
    && mkdir -p OpenSceneGraph/build \
    && cmake OpenSceneGraph -B OpenSceneGraph/build \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_OSG_APPLICATIONS=OFF \
    -DBUILD_OSG_DEPRECATED_SERIALIZERS=OFF \
    && cmake --build OpenSceneGraph/build --target install -j${NUM_CORES} \
    && rm -rf OpenSceneGraph
