/*
 * Copyright (c) 2011, The DART development contributors
 * All rights reserved.
 *
 * The list of contributors can be found at:
 *   https://github.com/dartsim/dart/blob/main/LICENSE
 *
 * This file is provided under the following "BSD-style" License:
 *   Redistribution and use in source and binary forms, with or
 *   without modification, are permitted provided that the following
 *   conditions are met:
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
 *   CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 *   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 *   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *   DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 *   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 *   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 *   AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *   LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *   ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *   POSSIBILITY OF SUCH DAMAGE.
 */

/// \file test_nonfinite_contact.cpp
/// \brief Regression test for gz-physics issue #1010:
///        https://github.com/gazebosim/gz-physics/issues/1010
///
/// A collision shape with a non-finite dimension produces a contact whose
/// point is non-finite (NaN). Before the fix this NaN propagated into
/// ContactConstraint's spatial Jacobian, tripping
/// `DART_ASSERT(!math::isNan(mSpatialNormalA))` in asserts-enabled builds and
/// silently corrupting the LCP solve (NaN residual, invalid-problem fallback)
/// in release builds.
///
/// The downstream report used an infinite-radius SphereShape. SphereShape now
/// rejects non-finite radii at construction, but the ContactConstraint
/// vulnerability is independent of any single shape: any collision detector,
/// mesh, or unvalidated primitive can emit a non-finite contact. This test
/// drives the same `collideSphereSphere` code path from the original stack
/// trace through an unvalidated EllipsoidShape (the DART collision detector
/// approximates an ellipsoid as a sphere of radius `getRadii()[0]`).
///
/// ConstraintSolver::updateConstraints() now skips non-finite contacts before
/// they reach contact-constraint creation. We verify that by counting how many
/// contacts are handed to the contact-surface handler: the degenerate contact
/// is still generated by collision detection, but it must never reach
/// constraint creation, and the solve must leave the simulation state finite.

#include "dart/collision/collision_result.hpp"
#include "dart/collision/dart/dart_collision_detector.hpp"
#include "dart/constraint/constraint_solver.hpp"
#include "dart/constraint/contact_surface.hpp"
#include "dart/dynamics/body_node.hpp"
#include "dart/dynamics/ellipsoid_shape.hpp"
#include "dart/dynamics/free_joint.hpp"
#include "dart/dynamics/shape_node.hpp"
#include "dart/dynamics/skeleton.hpp"
#include "dart/dynamics/sphere_shape.hpp"

#include <gtest/gtest.h>

#include <limits>

#include <cmath>

using namespace dart;
using namespace dart::dynamics;
using namespace dart::constraint;

namespace {

/// Contact-surface handler that counts how many contacts reach contact
/// constraint creation. ConstraintSolver only invokes the handler for contacts
/// that survive the validity filters in updateConstraints(), so the count is
/// exactly the number of contacts accepted into the solve.
class CountingContactSurfaceHandler : public DefaultContactSurfaceHandler
{
public:
  ContactConstraintPtr createConstraint(
      collision::Contact& contact,
      size_t numContactsOnCollisionObject,
      double timeStep) const override
  {
    ++mNumContactsCreated;
    return DefaultContactSurfaceHandler::createConstraint(
        contact, numContactsOnCollisionObject, timeStep);
  }

  mutable int mNumContactsCreated = 0;
};

/// Creates a single-body skeleton with a FreeJoint at the given position. When
/// `withDynamics` is false the body carries only a CollisionAspect, which keeps
/// a degenerate (infinite) collision shape from injecting non-finite inertia
/// into the test independently of the contact being exercised.
SkeletonPtr createBody(
    const std::string& name,
    const ShapePtr& shape,
    const Eigen::Vector3d& position,
    bool withDynamics)
{
  auto skeleton = Skeleton::create(name);
  auto* body = skeleton->createJointAndBodyNodePair<FreeJoint>().second;

  if (withDynamics) {
    body->createShapeNodeWith<CollisionAspect, DynamicsAspect>(shape);
  } else {
    body->createShapeNodeWith<CollisionAspect>(shape);
  }

  skeleton->setPositions(
      (Eigen::Vector6d() << 0, 0, 0, position.x(), position.y(), position.z())
          .finished());

  return skeleton;
}

} // namespace

//==============================================================================
// A degenerate shape with an infinite dimension yields a non-finite contact
// point. The constraint solver must drop it before contact-constraint creation
// instead of corrupting the solve.
TEST(NonFiniteContact, InfiniteShapeContactIsSkipped)
{
  const double inf = std::numeric_limits<double>::infinity();

  // Static base with an infinite-radius ellipsoid (no DynamicsAspect so its
  // degenerate inertia cannot affect the result). The DART collision detector
  // routes ellipsoids through the same sphere-sphere path as the originally
  // reported infinite SphereShape.
  auto badShape
      = std::make_shared<EllipsoidShape>(Eigen::Vector3d(inf, inf, inf));
  auto badBody = createBody(
      "bad_base", badShape, Eigen::Vector3d::Zero(), /*withDynamics=*/false);
  badBody->setMobile(false);

  // A normal falling body overlapping the base.
  auto goodShape = std::make_shared<SphereShape>(0.1);
  auto goodBody = createBody(
      "falling_weight",
      goodShape,
      Eigen::Vector3d(0.0, 0.0, 0.05),
      /*withDynamics=*/true);

  ConstraintSolver solver;
  solver.setTimeStep(0.001);
  solver.setCollisionDetector(collision::DartCollisionDetector::create());
  solver.addSkeleton(badBody);
  solver.addSkeleton(goodBody);

  auto handler = std::make_shared<CountingContactSurfaceHandler>();
  solver.addContactSurfaceHandler(handler);

  // Before the fix this aborts on an assertion (asserts-enabled builds) or runs
  // the LCP solver on a NaN system (release builds).
  ASSERT_NO_FATAL_FAILURE(solver.solve());

  // Collision detection still reports the overlap, and the contact it produces
  // is genuinely non-finite: this is what the solver must defend against.
  const auto& result = solver.getLastCollisionResult();
  ASSERT_GT(result.getNumContacts(), 0u);
  bool anyNonFinite = false;
  for (std::size_t i = 0; i < result.getNumContacts(); ++i) {
    if (!result.getContact(i).point.allFinite()
        || !result.getContact(i).normal.allFinite()
        || !std::isfinite(result.getContact(i).penetrationDepth)) {
      anyNonFinite = true;
    }
  }
  EXPECT_TRUE(anyNonFinite)
      << "Test setup no longer produces a non-finite contact";

  // The non-finite contact must be filtered before contact-constraint creation.
  EXPECT_EQ(handler->mNumContactsCreated, 0);

  // And the solve must leave the simulation state finite.
  EXPECT_TRUE(goodBody->getPositions().allFinite());
  EXPECT_TRUE(goodBody->getVelocities().allFinite());
  EXPECT_TRUE(badBody->getVelocities().allFinite());
}
