/*
 * Copyright (c) 2011-2021, The DART development contributors
 * All rights reserved.
 *
 * The list of contributors can be found at:
 *   https://github.com/dartsim/dart/blob/master/LICENSE
 *
 * This file is provided under the following "BSD-style" License:
 *   Redistribution and use in source and binary forms, with or
 *   without modification, are permitted provided that the following
 *   conditions are met:
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
 *   CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 *   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 *   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *   DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 *   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 *   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 *   AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *   LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *   ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *   POSSIBILITY OF SUCH DAMAGE.
 */

#pragma once

#include <map>

#include "dart/collision/CollisionDetector.hpp"
#include "dart/collision/fcl/FclTypes.hpp"
#include "dart/math/SmartPointer.hpp"

namespace dart {
namespace collision2 {

template <typename S_>
class FclCollisionDetector : public CollisionDetector<S_>
{
public:
  // Type aliases
  using S = S_;

  static std::shared_ptr<FclCollisionDetector> create();

  /// Whether to use analytic collision checking for primitive shapes.
  ///
  /// PRIMITIVE: Use FCL's analytic collision checking for primitive shapes.
  /// MESH: Don't use it. Instead, use approximate mesh shapes for the primitive
  /// shapes. The contact result is probably less accurate than the analytic
  /// result.
  ///
  /// Warning: FCL's primitive shape support is not complete. FCL 0.4.0 improved
  /// the support alot, but it still returns single contact point for a shape
  /// pair except for box-box collision. For this reason, we recommend using
  /// MESH until FCL fully supports primitive shapes.
  enum PrimitiveShape
  {
    PRIMITIVE = 0,
    MESH
  };

  /// Whether to use FCL's contact point computation.
  ///
  /// FCL: Use FCL's contact point computation.
  /// DART: Use DART's own contact point computation.
  ///
  /// Warning: FCL's contact computation is not correct. See:
  /// https://github.com/flexible-collision-library/fcl/issues/106
  /// We recommend using DART until it's fixed in FCL.
  enum ContactPointComputationMethod
  {
    FCL = 0,
    DART
  };

  /// Constructor
  virtual ~FclCollisionDetector();

  // Documentation inherited
  const std::string& getType() const override;

  /// Get collision detector type for this class
  static const std::string& getStaticType();

  // Documentation inherited
  CollisionGroupPtr<S> createCollisionGroup() override;

protected:
  /// Constructor
  FclCollisionDetector() = default;

  /// Returns ::fcl::CollisionGeometry associated with give Shape. New
  /// ::fcl::CollisionGeome will be created if it hasn't created yet.
  std::shared_ptr<dart::collision2::fcl::CollisionGeometry<S>>
  createFCLCollisionGeometry(math::ConstGeometryPtr shape);

private:
  /// Information for a shape that was generated by this collision detector
  struct ShapeInfo final
  {
    /// A weak reference to the shape
    std::weak_ptr<dart::collision2::fcl::CollisionGeometry<S>>
        fclCollisionGeometry;

    /// The last version of the shape, as known by this collision detector
    std::size_t lastKnownVersion;
  };

  std::shared_ptr<fcl::CollisionGeometry<S>> createFCLCollisionGeometryImpl(
      const math::ConstGeometryPtr& shape,
      FclCollisionDetector::PrimitiveShape type);

private:
  using Base = CollisionDetector<S>;
  using ShapeMap = std::map<math::ConstGeometryPtr, ShapeInfo>;

  ShapeMap mShapeMap;

  PrimitiveShape mPrimitiveShapeType;

  static typename Base::template Registrar<FclCollisionDetector<S>> mRegistrar;
};

extern template class FclCollisionDetector<double>;

} // namespace collision2
} // namespace dart

#include "dart/collision/fcl/detail/FclCollisionDetector-impl.hpp"
