from __future__ import annotations

from enum import IntEnum
from typing import Tuple

FIRST_USE_EVER: int


class Key(IntEnum):
    Escape: int


class IO:
    @property
    def framerate(self) -> float: ...


def get_io() -> IO: ...
def set_next_window_size(width: float, height: float, cond: int = ...) -> None: ...
def set_next_window_bg_alpha(alpha: float) -> None: ...
def begin(name: str, flags: int = ...) -> bool: ...
def end() -> None: ...
def text(text: str) -> None: ...
def button(label: str) -> bool: ...
def same_line() -> None: ...
def separator() -> None: ...
def slider_float(label: str, value: float, min: float, max: float) -> Tuple[bool, float]: ...
def is_key_down(key: Key | int) -> bool: ...
