parameters:
  numThreads: 4

steps:
  - script: docker pull $DOCKER_NAME
    displayName: "Pull dev container"
  - script: |
      docker run \
        -v $(Build.SourcesDirectory):$(Build.SourcesDirectory) \
        --env-file .ci/docker/env.list \
        $DOCKER_NAME \
        /bin/sh -c "cd $(Build.SourcesDirectory) && ./.ci/build.sh -j${{ parameters.numThreads }}"
    displayName: "Build"
