from __future__ import annotations
import typing
__all__: list[str] = ['Composite', 'LocalResource', 'LocalResourceRetriever', 'Observer', 'Resource', 'ResourceRetriever', 'Stopwatch', 'Subject', 'Uri', 'debug', 'error', 'fatal', 'info', 'split', 'tic', 'toLower', 'toUpper', 'toc', 'tocMS', 'tocNS', 'tocS', 'tocUS', 'trace', 'trim', 'trimLeft', 'trimRight', 'warn']
class Composite:
    def __init__(self) -> None_:
        ...
    def copyCompositePropertiesTo(self, outgoingProperties: ..., std_param_1: ..., std_param_2: ..., std_param_3: ..., std_param_4: ..., std_param_5: ..., std_param_6: ..., dart_param_1: ...) -> None_:
        ...
    def copyCompositeStateTo(self, outgoingStates: ..., std_param_7: ..., std_param_8: ..., std_param_9: ..., std_param_10: ..., std_param_11: ..., std_param_12: ..., dart_param_2: ...) -> None_:
        ...
    def duplicateAspects(self, fromComposite: Composite) -> None_:
        ...
    def getCompositeProperties(self) -> ...:
        ...
    def getCompositeState(self) -> ...:
        ...
    def matchAspects(self, otherComposite: Composite) -> None_:
        ...
    def setCompositeProperties(self, newProperties: ..., std_param_13: ..., std_param_14: ..., std_param_15: ..., std_param_16: ..., std_param_17: ..., std_param_18: ..., dart_param_3: ...) -> None_:
        ...
    def setCompositeState(self, newStates: ..., std_param_19: ..., std_param_20: ..., std_param_21: ..., std_param_22: ..., std_param_23: ..., std_param_24: ..., dart_param_4: ...) -> None_:
        ...
class LocalResource(Resource):
    def __init__(self, path: str) -> None_:
        ...
    def isGood(self) -> bool:
        ...
class LocalResourceRetriever(ResourceRetriever):
    def __init__(self) -> None_:
        ...
class Observer:
    pass
class Resource:
    def getSize(self) -> int:
        ...
    def read(self, buffer: capsule, size: int, count: int) -> int:
        ...
    def readAll(self) -> str:
        ...
    def seek(self, offset: int, origin: ...) -> bool:
        ...
    def tell(self) -> int:
        ...
class ResourceRetriever:
    def exists(self, uri: Uri) -> bool:
        ...
    def getFilePath(self, uri: Uri) -> str:
        ...
    def readAll(self, uri: Uri) -> str:
        ...
    def retrieve(self, uri: Uri) -> Resource:
        ...
class Stopwatch:
    def __init__(self, start: bool = True) -> None_:
        ...
    def elapsedMS(self) -> float:
        ...
    def elapsedNS(self) -> float:
        ...
    def elapsedS(self) -> float:
        ...
    def elapsedUS(self) -> float:
        ...
    def isStarted(self) -> bool:
        ...
    def print(self) -> None_:
        ...
    def reset(self) -> None_:
        ...
    def start(self) -> None_:
        ...
    def stop(self) -> None_:
        ...
class Subject:
    pass
class Uri:
    mAuthority: ...
    mFragment: ...
    mPath: ...
    mQuery: ...
    mScheme: ...
    @staticmethod
    def createFromPath(path: str) -> Uri:
        ...
    @staticmethod
    @typing.overload
    def createFromRelativeUri(base: str, relative: str) -> Uri:
        ...
    @staticmethod
    @typing.overload
    def createFromRelativeUri(base: str, relative: str, strict: bool) -> Uri:
        ...
    @staticmethod
    @typing.overload
    def createFromRelativeUri(base: Uri, relative: str) -> Uri:
        ...
    @staticmethod
    @typing.overload
    def createFromRelativeUri(base: Uri, relative: str, strict: bool) -> Uri:
        ...
    @staticmethod
    @typing.overload
    def createFromRelativeUri(base: Uri, relative: Uri) -> Uri:
        ...
    @staticmethod
    @typing.overload
    def createFromRelativeUri(base: Uri, relative: Uri, strict: bool) -> Uri:
        ...
    @staticmethod
    def createFromString(input: str) -> Uri:
        ...
    @staticmethod
    def createFromStringOrPath(input: str) -> Uri:
        ...
    @staticmethod
    @typing.overload
    def getRelativeUri(base: str, relative: str) -> str:
        ...
    @staticmethod
    @typing.overload
    def getRelativeUri(base: str, relative: str, strict: bool) -> str:
        ...
    @staticmethod
    @typing.overload
    def getRelativeUri(base: Uri, relative: str) -> str:
        ...
    @staticmethod
    @typing.overload
    def getRelativeUri(base: Uri, relative: str, strict: bool) -> str:
        ...
    @staticmethod
    @typing.overload
    def getRelativeUri(base: Uri, relative: Uri) -> str:
        ...
    @staticmethod
    @typing.overload
    def getRelativeUri(base: Uri, relative: Uri, strict: bool) -> str:
        ...
    @staticmethod
    def getUri(input: str) -> str:
        ...
    @typing.overload
    def __init__(self) -> None_:
        ...
    @typing.overload
    def __init__(self, input: str) -> None_:
        ...
    @typing.overload
    def __init__(self, input: str) -> None_:
        ...
    def clear(self) -> None_:
        ...
    def fromPath(self, path: str) -> bool:
        ...
    @typing.overload
    def fromRelativeUri(self, base: str, relative: str) -> bool:
        ...
    @typing.overload
    def fromRelativeUri(self, base: str, relative: str, strict: bool) -> bool:
        ...
    @typing.overload
    def fromRelativeUri(self, base: str, relative: str) -> bool:
        ...
    @typing.overload
    def fromRelativeUri(self, base: str, relative: str, strict: bool) -> bool:
        ...
    @typing.overload
    def fromRelativeUri(self, base: Uri, relative: str) -> bool:
        ...
    @typing.overload
    def fromRelativeUri(self, base: Uri, relative: str, strict: bool) -> bool:
        ...
    @typing.overload
    def fromRelativeUri(self, base: Uri, relative: str) -> bool:
        ...
    @typing.overload
    def fromRelativeUri(self, base: Uri, relative: str, strict: bool) -> bool:
        ...
    @typing.overload
    def fromRelativeUri(self, base: Uri, relative: Uri) -> bool:
        ...
    @typing.overload
    def fromRelativeUri(self, base: Uri, relative: Uri, strict: bool) -> bool:
        ...
    def fromString(self, input: str) -> bool:
        ...
    def fromStringOrPath(self, input: str) -> bool:
        ...
    def getFilesystemPath(self) -> str:
        ...
    def getPath(self) -> str:
        ...
    def toString(self) -> str:
        ...
def debug(arg0: str) -> None_:
    ...
def error(arg0: str) -> None_:
    ...
def fatal(arg0: str) -> None_:
    ...
def info(arg0: str) -> None_:
    ...
def split(str: str, delimiters: str = ' \n\r\t') -> list[str]:
    ...
def tic() -> None_:
    ...
def toLower(str: str) -> str:
    ...
def toUpper(str: str) -> str:
    ...
def toc(print: bool = False) -> float:
    ...
def tocMS(print: bool = False) -> float:
    ...
def tocNS(print: bool = False) -> float:
    ...
def tocS(print: bool = False) -> float:
    ...
def tocUS(print: bool = False) -> float:
    ...
def trace(arg0: str) -> None_:
    ...
def trim(str: str, whitespaces: str = ' \n\r\t') -> str:
    ...
def trimLeft(str: str, whitespaces: str = ' \n\r\t') -> str:
    ...
def trimRight(str: str, whitespaces: str = ' \n\r\t') -> str:
    ...
def warn(arg0: str) -> None_:
    ...
