ARG TARGETPLATFORM=linux/amd64
FROM --platform=$TARGETPLATFORM jslee02/dart-dev:archlinux-min-v6.14

USER builder

# ==============================================================================
# DART optional dependencies
# ==============================================================================
RUN yay -Syu --needed --noconfirm \
    bullet \
    coin-or-ipopt \
    freeglut \
    nlopt \
    octomap \
    opencl-clhpp \
    opencl-headers \
    opencl-icd-loader \
    openscenegraph \
    pagmo \
    spdlog \
    tinyxml2 \
    urdfdom

# ==============================================================================
# Python binding dependencies
# ==============================================================================
RUN yay -Syu --needed --noconfirm \
    python3 \
    python-pip \
    pybind11 \
    python-numpy \
    python-pytest \
    python-requests \
    python-setuptools

USER root

# ode
RUN git clone https://bitbucket.org/odedevs/ode.git -b 'master' \
    && mkdir -p ode/build \
    && cmake ode \
    -B ode/build \
    -DCMAKE_BUILD_TYPE=Release \
    -DODE_WITH_TESTS=OFF \
    -DODE_WITH_DEMOS=OFF \
    -DODE_WITH_LIBCCD=ON \
    -DODE_WITH_LIBCCD_SYSTEM=ON \
    -DODE_WITH_LIBCCD_BOX_CYL=OFF \
    -DODE_DOUBLE_PRECISION=ON \
    && cmake --build ode/build --target install -j${NUM_CORES} \
    && rm -rf ode
