# Use an Ubuntu base image
FROM ubuntu:22.04

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

# Install build dependencies, X11 libraries, CA certificates, and Wayland protocols
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    libx11-dev \
    libgl1-mesa-dev \
    libgtk-3-dev \
    xorg-dev \
    ca-certificates \
    wayland-protocols \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Clone the Tracy Profiler repository
RUN git clone --depth 1 https://github.com/wolfpld/tracy.git

# Build Tracy Profiler
WORKDIR /tracy/profiler/build/unix
RUN cmake ../.. && make

# Use the `entrypoint.sh` to start the profiler
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

# Reset the frontend to its default value
ENV DEBIAN_FRONTEND=