ARG TARGETPLATFORM=linux/amd64
FROM --platform=$TARGETPLATFORM ubuntu:noble

ARG DEBIAN_FRONTEND=noninteractive

# Use /bin/bash to use pushd/popd
SHELL ["/bin/bash", "-c"]

# Update apt-get
RUN apt-get update -qq

# ==============================================================================
# Build tools
# ==============================================================================
RUN apt-get install -y --no-install-recommends \
    build-essential \
    clang \
    clang-format-14 \
    cmake \
    curl \
    doxygen \
    git \
    lcov \
    lsb-release \
    ninja-build \
    pkg-config \
    software-properties-common \
    valgrind

# ==============================================================================
# DART required dependencies
# ==============================================================================
RUN apt-get install -y --no-install-recommends \
    libassimp-dev \
    libeigen3-dev \
    libfcl-dev \
    libfmt-dev

# ==============================================================================
# DART optional dependencies
# ==============================================================================

RUN apt-get install -y --no-install-recommends \
    coinor-libipopt-dev \
    freeglut3-dev \
    libxi-dev \
    libxmu-dev \
    libbullet-dev \
    libtinyxml2-dev \
    liburdfdom-dev \
    liburdfdom-headers-dev \
    libopenscenegraph-dev \
    libnlopt-cxx-dev \
    liboctomap-dev \
    libode-dev \
    libimgui-dev \
    libspdlog-dev \
    libpagmo-dev

# ==============================================================================
# Python binding dependencies
# ==============================================================================

RUN apt-get install -y --no-install-recommends \
    libpython3-dev \
    pybind11-dev \
    python3 \
    python3-dev \
    python3-numpy \
    python3-pip \
    python3-pytest \
    python3-setuptools

# ==============================================================================
# Clean up
# ==============================================================================

RUN rm -rf /var/lib/apt/lists/*
