ARG BASE_IMAGE=quay.io/pypa/manylinux2014_x86_64
FROM $BASE_IMAGE

ARG NUM_CORES=14

RUN yum install -y \
    boost-devel \
    bullet-devel \
    coin-or-Ipopt-devel \
    doxygen \
    fmt-devel \
    freeglut-devel \
    glew-devel \
    libccd-devel \
    python3-devel \
    spdlog-devel \
    tinyxml-devel

# assimp
RUN git clone https://github.com/assimp/assimp.git -b 'v5.2.5' \
    && mkdir -p assimp/build \
    && cmake assimp -B assimp/build -DCMAKE_BUILD_TYPE=Release -DASSIMP_BUILD_TESTS=OFF -DASSIMP_WARNINGS_AS_ERRORS=OFF \
    && cmake --build assimp/build --target install -j${NUM_CORES} \
    && rm -rf assimp

# eigen
RUN git clone https://gitlab.com/libeigen/eigen.git -b '3.4.0' \
    && mkdir -p eigen/build \
    && cmake eigen -B eigen/build -DCMAKE_BUILD_TYPE=Release -DEIGEN_BUILD_TESTING=OFF -DEIGEN_BUILD_DOC=OFF \
    && cmake --build eigen/build --target install -j${NUM_CORES} \
    && rm -rf eigen

# nlopt
RUN git clone https://github.com/stevengj/nlopt.git -b 'v2.7.1' \
    && mkdir -p nlopt/build \
    && cmake nlopt -B nlopt/build -DCMAKE_BUILD_TYPE=Release \
    && cmake --build nlopt/build --target install -j${NUM_CORES} \
    && rm -rf nlopt

# octomap
RUN git clone https://github.com/OctoMap/octomap.git -b 'v1.9.6' \
    && mkdir -p octomap/build \
    && cmake octomap -B octomap/build -DCMAKE_BUILD_TYPE=Release -DBUILD_OCTOVIS_SUBPROJECT=OFF -DBUILD_OCTOVIS_SUBPROJECT=OFF -DBUILD_DYNAMICETD3D_SUBPROJECT=OFF -DBUILD_TESTING=OFF \
    && cmake --build octomap/build --target install -j${NUM_CORES} \
    && rm -rf octomap

# fcl
RUN git clone https://github.com/flexible-collision-library/fcl.git -b '0.7.0' \
    && mkdir -p fcl/build \
    && cmake fcl -B fcl/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF \
    && cmake --build fcl/build --target install -j${NUM_CORES} \
    && rm -rf fcl

# ODE
RUN git clone https://bitbucket.org/odedevs/ode.git -b '0.16.3' \
    && mkdir -p ode/build \
    && cmake ode -B ode/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF \
    && cmake --build ode/build --target install -j${NUM_CORES} \
    && rm -rf ode

# tinyxml2
RUN git clone https://github.com/leethomason/tinyxml2.git -b '9.0.0' \
    && mkdir -p tinyxml2/build \
    && cmake tinyxml2 -B tinyxml2/build -DCMAKE_BUILD_TYPE=Release -Dtinyxml2_BUILD_TESTING=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    && cmake --build tinyxml2/build --target install -j${NUM_CORES} \
    && rm -rf tinyxml2

# console_bridge
RUN git clone https://github.com/ros/console_bridge.git -b 1.0.2 \
    && mkdir -p console_bridge/build \
    && cmake console_bridge -B console_bridge/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF \
    && cmake --build console_bridge/build --target install -j${NUM_CORES} \
    && rm -rf console_bridge

# urdfdom_headers
RUN git clone https://github.com/ros/urdfdom_headers.git -b 1.0.5 \
    && mkdir -p urdfdom_headers/build \
    && cmake urdfdom_headers -B urdfdom_headers/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF \
    && cmake --build urdfdom_headers/build --target install -j${NUM_CORES} \
    && rm -rf urdfdom_headers

# urdfdom
RUN git clone https://github.com/ros/urdfdom.git -b 3.0.0 \
    && mkdir -p urdfdom/build \
    && cmake urdfdom -B urdfdom/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF \
    && cmake --build urdfdom/build --target install -j${NUM_CORES} \
    && rm -rf urdfdom

# openscenegraph
RUN git clone https://github.com/openscenegraph/OpenSceneGraph.git \
    && mkdir -p OpenSceneGraph/build \
    && cmake OpenSceneGraph -B OpenSceneGraph/build \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_OSG_APPLICATIONS=OFF \
    -DBUILD_OSG_DEPRECATED_SERIALIZERS=OFF \
    && cmake --build OpenSceneGraph/build --target install -j${NUM_CORES} \
    && rm -rf OpenSceneGraph

# pybind11
RUN git clone https://github.com/pybind/pybind11.git -b 'v2.10.3' \
    && mkdir -p pybind11/build \
    && cmake pybind11 -B pybind11/build -DCMAKE_BUILD_TYPE=Release -DPYBIND11_TEST=OFF \
    && cmake --build pybind11/build --target install -j${NUM_CORES} \
    && rm -rf pybind11
