# Use an Ubuntu base image
FROM ubuntu:22.04

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

# Install build dependencies, X11 libraries, CA certificates, and Wayland protocols
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    libx11-dev \
    libgl1-mesa-dev \
    libgtk-3-dev \
    libglfw3-dev \
    xorg-dev \
    ca-certificates \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Build Tracy Profiler
# TODO: Change to a fixed version once > 0.10 is released
RUN git clone --depth 1 https://github.com/wolfpld/tracy.git -b master \
    && cmake -S tracy/profiler -B tracy/profiler/build -DCMAKE_BUILD_TYPE=Release -DLEGACY=ON \
    && cmake --build tracy/profiler/build --target install -j

# Reset the frontend to its default value
ENV DEBIAN_FRONTEND=

USER 1000

ENTRYPOINT ["tracy/profiler/build/tracy-profiler"]
