ARG TARGETPLATFORM=linux/amd64
FROM --platform=$TARGETPLATFORM jslee02/dart-dev:archlinux-min-v7.0

USER builder

# ==============================================================================
# DART optional dependencies
# ==============================================================================
RUN yay -Syu --needed --noconfirm \
    bullet \
    coin-or-ipopt \
    freeglut \
    nlopt \
    octomap \
    ode \
    opencl-clhpp \
    opencl-headers \
    opencl-icd-loader \
    openscenegraph \
    pagmo \
    spdlog \
    tinyxml2 \
    urdfdom

# ==============================================================================
# Python binding dependencies
# ==============================================================================
RUN yay -Syu --needed --noconfirm \
    python3 \
    python-pip \
    pybind11 \
    python-numpy \
    python-pytest \
    python-requests \
    python-setuptools

USER root
