ARG TARGETPLATFORM=linux/amd64
FROM --platform=$TARGETPLATFORM archlinux:latest

#===============================================================================
# Install packages only available in pacman
#===============================================================================
RUN pacman -Syuq --noconfirm glu

#===============================================================================
# Install yay
#===============================================================================
RUN pacman -Syuq --noconfirm git base-devel sudo go
RUN echo "Defaults        lecture = never" > /etc/sudoers.d/privacy \
    && echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/wheel \
    && useradd -m -G wheel -s /bin/bash builder
USER builder
WORKDIR /home/builder
RUN git clone https://aur.archlinux.org/yay.git --single-branch --depth 1 \
    && cd yay \
    && makepkg -si --noconfirm \
    && cd .. \
    && rm -rf .cache yay

#===============================================================================
# Build tools
#===============================================================================
RUN yay -Syu --needed --noconfirm \
    clang \
    cmake \
    doxygen \
    valgrind

# ==============================================================================
# DART required dependencies
# ==============================================================================
RUN yay -Syu --needed --noconfirm \
    assimp eigen fcl fmt libccd

USER root
