ARG BASE_IMAGE=jslee02/dart-dev:manylinux_2_28_s390x-min-v7.0
FROM $BASE_IMAGE

ARG NUM_CORES=14

# Missing optional dependencies:
#   ipopt

# openscenegraph
RUN git clone https://github.com/openscenegraph/OpenSceneGraph.git \
    && mkdir -p OpenSceneGraph/build \
    && cmake OpenSceneGraph -B OpenSceneGraph/build \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_OSG_APPLICATIONS=OFF \
    -DBUILD_OSG_DEPRECATED_SERIALIZERS=OFF \
    && cmake --build OpenSceneGraph/build --target install -j${NUM_CORES} \
    && rm -rf OpenSceneGraph
