code:
  - "**"
  - "!.github/workflows/update_lockfiles.yml"
  - "!docker/dev/**"
  - "!docs/**"
  - "!.readthedocs.yml"
  - "!tutorials/**"
  - "!**/*.md"
  - "!**/*.rst"
  - "!**/*.po"
  - "!**/*.pot"
