// This file is automatically generated from CMake
#ifndef UTILS_PATHS_H
#define UTILS_PATHS_H

#define DART_ROOT_PATH "C:/Users/Mike/Desktop/dart/"
#define DART_DATA_PATH "C:/Users/Mike/Desktop/dart/data/"

#endif // ifndef UTILS_PATHS_H
