// This file is automatically generated from CMake
#ifndef UTILS_PATHS_H
#define UTILS_PATHS_H

#define DART_ROOT_PATH "/home/ana/Software/dart/"
#define DART_DATA_PATH "/home/ana/Software/dart/data/"

#endif // ifndef UTILS_PATHS_H
