// This file is automatically generated from CMake
#ifndef UTILS_PATHS_H
#define UTILS_PATHS_H

#define DART_ROOT_PATH "/Users/karenliu/Research/dart/"
#define DART_DATA_PATH "/Users/karenliu/Research/dart/data/"

#endif // ifndef UTILS_PATHS_H
