#!/usr/bin/env python3
"""Enforce repository documentation content policies."""

from __future__ import annotations

import re
import sys
from pathlib import Path

SKIP_DIRS = {".deps", ".git", ".pixi", "build", "external", "node_modules"}
REQUIRED_DOCS_TOP_LEVEL_DIRS = (
    "ai",
    "assets",
    "background",
    "design",
    "dev_tasks",
    "doxygen",
    "onboarding",
    "plans",
    "python_api",
    "readthedocs",
)

# These strings have shown up as "footer metadata" in Markdown docs and should
# not be committed to the repository.
FORBIDDEN_FOOTER_MARKERS = (
    "**Generated**:",
    "**Project Version**:",
    "**Maintainer**:",
    "**Document Generated:**",
    "**DART Version:**",
    "**Analysis Complete**",
)

PLAN_FILE_RE = re.compile(r"^\d{3}-.+\.md$")
PLAN_BLOCK_RE = re.compile(
    r"^### (?P<id>PLAN-\d{3}):.*?(?=^### PLAN-\d{3}:|\Z)",
    re.MULTILINE | re.DOTALL,
)
DASHBOARD_FIELD_RE = re.compile(
    r"^- (Status|Horizon|Dimension|Next step|Gate):", re.MULTILINE
)
DESIGN_DASHBOARD_FIELD_RE = re.compile(
    r"^- (Priority|Horizon|Next step|Gate):", re.MULTILINE
)
DASHBOARD_REQUIRED_FIELDS = (
    "owner",
    "status",
    "horizon",
    "dimension",
    "next_step",
    "gate",
)
DASHBOARD_STATUS_VALUES = {"Proposed", "Active", "Blocked", "Complete", "Parked"}
DASHBOARD_HORIZON_VALUES = {"Now", "Next", "Later", "Parked"}


def iter_markdown_files(repo_root: Path) -> list[Path]:
    files: list[Path] = []
    for path in repo_root.rglob("*.md"):
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        files.append(path)
    return sorted(files)


def check_file(path: Path, repo_root: Path) -> list[str]:
    rel_path = str(path.relative_to(repo_root))
    text = path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()

    failures: list[str] = []

    # Footer marker checks: only scan the tail to avoid false positives in body
    # text (e.g., "generated by X" as part of an explanation).
    tail_len = min(len(lines), 80)
    tail_offset = len(lines) - tail_len
    for index, line in enumerate(lines[tail_offset:], start=tail_offset + 1):
        for marker in FORBIDDEN_FOOTER_MARKERS:
            if marker in line:
                failures.append(
                    f"{rel_path}:{index}: disallowed footer marker {marker!r}"
                )
                break

    return failures


def check_docs_indexes(repo_root: Path) -> list[str]:
    """Ensure tracked top-level docs buckets stay visible from docs indexes."""
    failures: list[str] = []
    docs_readme = repo_root / "docs" / "README.md"
    docs_agents = repo_root / "docs" / "AGENTS.md"

    for path in (docs_readme, docs_agents):
        if not path.exists():
            failures.append(f"{path.relative_to(repo_root)}: missing docs index")
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for directory in REQUIRED_DOCS_TOP_LEVEL_DIRS:
            marker = f"{directory}/"
            if marker not in text:
                failures.append(
                    f"{path.relative_to(repo_root)}: missing `{marker}` entry"
                )

    return failures


def check_dev_task_shape(repo_root: Path) -> list[str]:
    """Ensure active dev-task folders include status and resume context."""
    failures: list[str] = []
    dev_tasks_dir = repo_root / "docs" / "dev_tasks"
    if not dev_tasks_dir.exists():
        return failures

    for task_dir in sorted(path for path in dev_tasks_dir.iterdir() if path.is_dir()):
        for required in ("README.md", "RESUME.md"):
            required_path = task_dir / required
            if not required_path.exists():
                failures.append(
                    f"{task_dir.relative_to(repo_root)}: missing required {required}"
                )

    return failures


def _dashboard_entries(text: str) -> list[dict[str, str]]:
    entries: list[dict[str, str]] = []
    for match in PLAN_BLOCK_RE.finditer(text):
        block = match.group(0)
        status_match = re.search(r"^- Status:\s*(?P<status>.+)$", block, re.MULTILINE)
        horizon_match = re.search(
            r"^- Horizon:\s*(?P<horizon>.+)$", block, re.MULTILINE
        )
        dimension_match = re.search(
            r"^- Dimension:\s*(?P<dimension>.+)$", block, re.MULTILINE
        )
        next_step_match = re.search(
            r"^- Next step:\s*(?P<next_step>.+)$", block, re.MULTILINE
        )
        gate_match = re.search(r"^- Gate:\s*(?P<gate>.+)$", block, re.MULTILINE)
        owner_match = re.search(
            r"- Owner doc:.*?\]\((?P<owner>[^)]+)\)",
            block,
            re.DOTALL,
        )
        entries.append(
            {
                "id": match.group("id"),
                "status": status_match.group("status").strip() if status_match else "",
                "horizon": (
                    horizon_match.group("horizon").strip() if horizon_match else ""
                ),
                "dimension": (
                    dimension_match.group("dimension").strip()
                    if dimension_match
                    else ""
                ),
                "next_step": (
                    next_step_match.group("next_step").strip()
                    if next_step_match
                    else ""
                ),
                "gate": gate_match.group("gate").strip() if gate_match else "",
                "owner": owner_match.group("owner").strip() if owner_match else "",
            }
        )
    return entries


def _normalize_plan_owner(owner: str) -> str:
    return owner.split("#", maxsplit=1)[0].strip()


def _is_external_link(link: str) -> bool:
    return "://" in link or link.startswith("mailto:")


def _resolve_dashboard_owner(
    owner: str, repo_root: Path, plans_dir: Path
) -> Path | None:
    target = _normalize_plan_owner(owner)
    if not target or _is_external_link(target):
        return None

    target_path = Path(target)
    if target_path.is_absolute():
        return target_path.resolve()

    if target_path.parts[:2] == ("docs", "plans"):
        return (repo_root / target_path).resolve()
    if target_path.parts[:1] == ("plans",):
        return (repo_root / "docs" / target_path).resolve()
    return (plans_dir / target_path).resolve()


def _direct_numbered_plan_file(owner_path: Path, plans_dir: Path) -> str | None:
    try:
        rel_path = owner_path.relative_to(plans_dir.resolve())
    except ValueError:
        return None

    if len(rel_path.parts) == 1 and PLAN_FILE_RE.match(rel_path.name):
        return rel_path.name
    return None


def _resolve_markdown_link(link: str, base_dir: Path) -> Path | None:
    target = _normalize_plan_owner(link)
    if not target or _is_external_link(target):
        return None

    target_path = Path(target)
    if target_path.is_absolute():
        return target_path.resolve()
    return (base_dir / target_path).resolve()


def check_plan_id_uniqueness(entries: list[dict[str, str]]) -> list[str]:
    """PLAN-091 WP-091.5: each PLAN-ID identifies exactly one dashboard block.

    A colliding ID (two initiatives sharing one ``PLAN-NNN``) makes grep-by-ID
    ambiguous and breaks the packet-execution harness, so reject it.
    """
    counts: dict[str, int] = {}
    order: list[str] = []
    for entry in entries:
        plan_id = entry["id"]
        if plan_id not in counts:
            order.append(plan_id)
        counts[plan_id] = counts.get(plan_id, 0) + 1
    failures: list[str] = []
    for plan_id in order:
        if counts[plan_id] > 1:
            failures.append(
                "docs/plans/dashboard.md: "
                f"{plan_id} identifies {counts[plan_id]} dashboard blocks; each "
                "PLAN-ID must identify exactly one initiative (renumber the "
                "colliding entries onto fresh IDs)"
            )
    return failures


def check_plan_lifecycle(repo_root: Path) -> list[str]:
    """Ensure living plans stay current instead of becoming archival state."""
    failures: list[str] = []
    plans_dir = repo_root / "docs" / "plans"
    dashboard = plans_dir / "dashboard.md"
    if not plans_dir.exists() or not dashboard.exists():
        return failures

    plan_files = {
        path.name for path in plans_dir.glob("*.md") if PLAN_FILE_RE.match(path.name)
    }
    dashboard_text = dashboard.read_text(encoding="utf-8", errors="replace")
    entries = _dashboard_entries(dashboard_text)
    failures.extend(check_plan_id_uniqueness(entries))

    referenced_plan_files: set[str] = set()
    for entry in entries:
        for field in DASHBOARD_REQUIRED_FIELDS:
            if not entry[field]:
                failures.append(
                    "docs/plans/dashboard.md: "
                    f"{entry['id']} is missing required `{field}` field"
                )
        if entry["status"] and entry["status"] not in DASHBOARD_STATUS_VALUES:
            failures.append(
                "docs/plans/dashboard.md: "
                f"{entry['id']} has unknown status `{entry['status']}`"
            )
        if entry["horizon"] and entry["horizon"] not in DASHBOARD_HORIZON_VALUES:
            failures.append(
                "docs/plans/dashboard.md: "
                f"{entry['id']} has unknown horizon `{entry['horizon']}`"
            )
        owner = _normalize_plan_owner(entry["owner"])
        owner_path = _resolve_dashboard_owner(owner, repo_root, plans_dir)
        if owner_path:
            try:
                owner_path.relative_to(repo_root.resolve())
            except ValueError:
                failures.append(
                    "docs/plans/dashboard.md: "
                    f"{entry['id']} owner doc escapes repository: `{owner}`"
                )
            else:
                if not owner_path.exists():
                    failures.append(
                        "docs/plans/dashboard.md: "
                        f"{entry['id']} owner doc does not exist: `{owner}`"
                    )
        owner_plan_file = (
            _direct_numbered_plan_file(owner_path, plans_dir) if owner_path else None
        )
        if owner_plan_file:
            referenced_plan_files.add(owner_plan_file)
            if entry["status"] == "Complete":
                failures.append(
                    "docs/plans/dashboard.md: completed "
                    f"{entry['id']} still points to numbered plan file "
                    f"`{owner}`; move durable output to its owner doc and "
                    "retarget or remove the plan entry"
                )

    for plan_file in sorted(plan_files - referenced_plan_files):
        failures.append(
            f"docs/plans/{plan_file}: numbered plan file is not referenced "
            "from docs/plans/dashboard.md"
        )

    for plan_file in sorted(plan_files):
        path = plans_dir / plan_file
        text = path.read_text(encoding="utf-8", errors="replace")
        repeated_field = DASHBOARD_FIELD_RE.search(text)
        if repeated_field:
            line = text.count("\n", 0, repeated_field.start()) + 1
            failures.append(
                f"docs/plans/{plan_file}:{line}: plan file repeats dashboard "
                f"field `{repeated_field.group(1)}`"
            )

    return failures


def check_design_docs_index(repo_root: Path) -> list[str]:
    """Ensure durable design docs stay discoverable and non-roadmap-shaped."""
    failures: list[str] = []
    design_dir = repo_root / "docs" / "design"
    if not design_dir.exists():
        return failures

    readme = design_dir / "README.md"
    agents = design_dir / "AGENTS.md"
    for required in (readme, agents):
        if not required.exists():
            failures.append(
                f"{required.relative_to(repo_root)}: missing design index/rules file"
            )

    readme_text = (
        readme.read_text(encoding="utf-8", errors="replace") if readme.exists() else ""
    )
    readme_links: set[str] = set()
    for match in re.finditer(r"\[[^\]]+\]\((?P<link>[^)]+)\)", readme_text):
        linked_path = _resolve_markdown_link(match.group("link"), design_dir)
        if not linked_path:
            continue
        try:
            rel_path = linked_path.relative_to(design_dir.resolve())
        except ValueError:
            continue
        if len(rel_path.parts) == 1:
            readme_links.add(rel_path.name)
    for design_doc in sorted(design_dir.glob("*.md")):
        if design_doc.name in {"README.md", "AGENTS.md"}:
            continue
        rel_path = design_doc.relative_to(repo_root)
        if design_doc.name not in readme_links:
            failures.append(f"{rel_path}: missing from docs/design/README.md")

        text = design_doc.read_text(encoding="utf-8", errors="replace")
        repeated_field = DESIGN_DASHBOARD_FIELD_RE.search(text)
        if repeated_field:
            line = text.count("\n", 0, repeated_field.start()) + 1
            failures.append(
                f"{rel_path}:{line}: design doc repeats dashboard field "
                f"`{repeated_field.group(1)}`"
            )

    return failures


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    failures: list[str] = []
    for path in iter_markdown_files(repo_root):
        failures.extend(check_file(path, repo_root))
    failures.extend(check_docs_indexes(repo_root))
    failures.extend(check_dev_task_shape(repo_root))
    failures.extend(check_plan_lifecycle(repo_root))
    failures.extend(check_design_docs_index(repo_root))

    if not failures:
        return 0

    print("Documentation policy check failed:", file=sys.stderr)
    for failure in failures:
        print(f"  - {failure}", file=sys.stderr)
    print("\nFix the documentation policy failures listed above.", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
