# DART API Documentation Build Configuration

# Version selection strategy
version_strategy: auto  # Options: auto, manual, latest_n

# Auto-discovery settings (when version_strategy: auto)
auto_discover:
  # Git tag pattern to match (regex)
  tag_pattern: '^v6\.\d+\.\d+$'  # Matches v6.x.y (excludes alpha, beta, rc)

  # Minimum version to include (optional)
  min_version: v6.9.0

  # Maximum number of versions to build (null = all)
  max_versions: null

  # Sort order for versions (when max_versions is set)
  sort_order: desc  # desc (newest first) or asc (oldest first)

# Manual version list (when version_strategy: manual)
# Only used if version_strategy is set to 'manual'
manual_versions:
  - section: DART 6
    versions:
      - v6.13.2
      - v6.12.2
      - v6.11.1
      - v6.10.1
      - v6.10.0
      - v6.9.5
      - v6.9.4
      - v6.9.2

# Latest N strategy (when version_strategy: latest_n)
latest_n:
  count: 5  # Number of most recent versions to build
  tag_pattern: '^v6\.\d+\.\d+$'

# Version grouping for index page
grouping:
  enabled: true
  # Group versions by major.minor (e.g., v6.13.x)
  by: major_minor
  # Custom section headers
  sections:
    - name: DART 6.13
      pattern: '^v6\.13\.\d+$'
    - name: DART 6.12
      pattern: '^v6\.12\.\d+$'
    - name: DART 6.11
      pattern: '^v6\.11\.\d+$'
    - name: DART 6.10
      pattern: '^v6\.10\.\d+$'
    - name: DART 6.9
      pattern: '^v6\.9\.\d+$'

# Build options
build:
  # Build C++ documentation
  cpp: true

  # Build Python documentation
  python: true

  # Continue building other versions if one fails
  continue_on_error: true

  # Parallel builds (number of versions to build in parallel)
  # Set to 1 for sequential builds
  parallel: 1

# Documentation output
output:
  # C++ documentation suffix (e.g., v6.13.2/ for C++)
  cpp_suffix: ''

  # Python documentation suffix (e.g., v6.13.2-python/ for Python)
  python_suffix: -python

  # Index file name
  index_file: index.md
