from __future__ import annotations

__all__: list[str] = [
    "AdmmSolver",
    "AdmmSolverParameters",
    "AngleAxis",
    "ApgdSolver",
    "ApgdSolverParameters",
    "BaraffSolver",
    "BgsSolver",
    "BgsSolverParameters",
    "BlockedJacobiSolver",
    "BlockedJacobiSolverParameters",
    "BoxedSemiSmoothNewtonSolver",
    "BoxedSemiSmoothNewtonSolverParameters",
    "DantzigSolver",
    "DirectSolver",
    "FischerBurmeisterNewtonSolver",
    "FischerBurmeisterNewtonSolverParameters",
    "InteriorPointSolver",
    "InteriorPointSolverParameters",
    "Isometry3",
    "JacobiSolver",
    "JacobiSolverParameters",
    "LcpOptions",
    "LcpProblem",
    "LcpProblemType",
    "LcpResult",
    "LcpSolver",
    "LcpSolverStatus",
    "LemkeSolver",
    "MinimumMapNewtonSolver",
    "MinimumMapNewtonSolverParameters",
    "MprgpSolver",
    "MprgpSolverParameters",
    "NncgSolver",
    "NncgSolverParameters",
    "PenalizedFischerBurmeisterNewtonSolver",
    "PenalizedFischerBurmeisterNewtonSolverParameters",
    "PgsSolver",
    "PgsSolverParameters",
    "Quaternion",
    "Random",
    "RedBlackGaussSeidelSolver",
    "RedBlackGaussSeidelSolverParameters",
    "SE3",
    "SE3Tangent",
    "SO3",
    "SO3Tangent",
    "SapSolver",
    "SapSolverParameters",
    "ShockPropagationSolver",
    "ShockPropagationSolverParameters",
    "StaggeringSolver",
    "SubspaceMinimizationSolver",
    "SubspaceMinimizationSolverParameters",
    "SymmetricPsorSolver",
    "SymmetricPsorSolverParameters",
    "TgsSolver",
    "TgsSolverParameters",
    "TriMesh",
    "deg2rad",
    "eps",
    "eulerXYXToMatrix",
    "eulerXYZToMatrix",
    "eulerXZXToMatrix",
    "eulerXZYToMatrix",
    "eulerYXYToMatrix",
    "eulerYXZToMatrix",
    "eulerYZXToMatrix",
    "eulerYZYToMatrix",
    "eulerZXYToMatrix",
    "eulerZXZToMatrix",
    "eulerZYXToMatrix",
    "eulerZYZToMatrix",
    "euler_xyx_to_matrix",
    "euler_xyz_to_matrix",
    "euler_xzx_to_matrix",
    "euler_xzy_to_matrix",
    "euler_yxy_to_matrix",
    "euler_yxz_to_matrix",
    "euler_yzx_to_matrix",
    "euler_yzy_to_matrix",
    "euler_zxy_to_matrix",
    "euler_zxz_to_matrix",
    "euler_zyx_to_matrix",
    "euler_zyz_to_matrix",
    "exp",
    "expAngular",
    "expMap",
    "expMapJac",
    "expMapRot",
    "expToQuat",
    "exp_angular",
    "exp_map",
    "exp_map_jac",
    "exp_map_rot",
    "exp_to_quat",
    "half_pi",
    "inf",
    "lcp_problem_type_to_string",
    "lcp_solver_status_to_string",
    "log",
    "matrixToEulerXYX",
    "matrixToEulerXYZ",
    "matrixToEulerXZY",
    "matrixToEulerYXZ",
    "matrixToEulerYZX",
    "matrixToEulerZXY",
    "matrixToEulerZYX",
    "matrix_to_euler_xyx",
    "matrix_to_euler_xyz",
    "matrix_to_euler_xzy",
    "matrix_to_euler_yxz",
    "matrix_to_euler_yzx",
    "matrix_to_euler_zxy",
    "matrix_to_euler_zyx",
    "max_val",
    "min_val",
    "phi",
    "pi",
    "pi_sq",
    "quatToExp",
    "quat_to_exp",
    "rad2deg",
    "rand_se3",
    "rand_se3_tangent",
    "rand_so3",
    "rand_so3_tangent",
    "two_pi",
    "verifyRotation",
    "verifyTransform",
    "verify_rotation",
    "verify_transform",
]


from collections.abc import Sequence
import enum
from typing import Annotated, Any, TypeAlias, overload

import numpy
from numpy.typing import NDArray


pi: float = ...

two_pi: float = ...

half_pi: float = ...

pi_sq: float = ...

phi: float = ...

inf: float = ...

max_val: float = ...

min_val: float = ...

eps: float = ...

def deg2rad(degrees: float) -> float: ...

def rad2deg(radians: float) -> float: ...

class Random:
    def __init__(self) -> None: ...

    def setSeed(*args, **kwargs): ...

    def getSeed(*args, **kwargs): ...

    @staticmethod
    def uniform(min: float, max: float) -> float: ...

    get_seed = getSeed

    set_seed = setSeed

def eulerXYXToMatrix(*args, **kwargs): ...

def eulerXYZToMatrix(*args, **kwargs): ...

def eulerXZXToMatrix(*args, **kwargs): ...

def eulerXZYToMatrix(*args, **kwargs): ...

def eulerYXYToMatrix(*args, **kwargs): ...

def eulerYXZToMatrix(*args, **kwargs): ...

def eulerYZXToMatrix(*args, **kwargs): ...

def eulerYZYToMatrix(*args, **kwargs): ...

def eulerZXYToMatrix(*args, **kwargs): ...

def eulerZYXToMatrix(*args, **kwargs): ...

def eulerZXZToMatrix(*args, **kwargs): ...

def eulerZYZToMatrix(*args, **kwargs): ...

def matrixToEulerXYX(*args, **kwargs): ...

def matrixToEulerXYZ(*args, **kwargs): ...

def matrixToEulerXZY(*args, **kwargs): ...

def matrixToEulerYXZ(*args, **kwargs): ...

def matrixToEulerYZX(*args, **kwargs): ...

def matrixToEulerZXY(*args, **kwargs): ...

def matrixToEulerZYX(*args, **kwargs): ...

def expMap(*args, **kwargs): ...

def expMapJac(*args, **kwargs): ...

def expMapRot(*args, **kwargs): ...

def expToQuat(*args, **kwargs): ...

def quatToExp(*args, **kwargs): ...

def expAngular(*args, **kwargs): ...

def verifyRotation(*args, **kwargs): ...

def verifyTransform(*args, **kwargs): ...

class Isometry3:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, matrix: Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]) -> None: ...

    @overload
    def __init__(self, rotation: Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')], translation: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> None: ...

    @overload
    def __init__(self, rotation: Quaternion, translation: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> None: ...

    def Identity(*args, **kwargs): ...

    def matrix(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]: ...

    def set_identity(self) -> None: ...

    def set_matrix(self, matrix: Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]) -> None: ...

    def translation(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def set_translation(self, translation: object) -> None: ...

    def rotation(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    def set_rotation(self, rotation: Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]) -> None: ...

    def quaternion(self) -> Quaternion: ...

    def set_quaternion(self, quaternion: Quaternion) -> None: ...

    def __str__(self) -> str: ...

    @overload
    def multiply(self, other: Isometry3) -> Isometry3: ...

    @overload
    def multiply(self, position: object) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def inverse(self) -> Isometry3: ...

    def translate(self, shift: object) -> None: ...

    def pretranslate(self, shift: object) -> None: ...

    identity = Identity

class Quaternion:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, wxyz: Annotated[NDArray[numpy.float64], dict(shape=(4), order='C')]) -> None: ...

    @overload
    def __init__(self, w: float, x: float, y: float, z: float) -> None: ...

    @overload
    def __init__(self, rotation: Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]) -> None: ...

    def Identity(*args, **kwargs): ...

    def w(self) -> float: ...

    def x(self) -> float: ...

    def y(self) -> float: ...

    def z(self) -> float: ...

    def xyz(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def wxyz(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4), order='C')]: ...

    def set_wxyz(self, wxyz: Annotated[NDArray[numpy.float64], dict(shape=(4), order='C')]) -> None: ...

    def rotation(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    def set_rotation(self, rotation: Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]) -> None: ...

    def __str__(self) -> str: ...

    @overload
    def multiply(self, other: Quaternion) -> Quaternion: ...

    @overload
    def multiply(self, position: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def inverse(self) -> Quaternion: ...

    def conjugate(self) -> Quaternion: ...

    def to_rotation_matrix(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    identity = Identity

class AngleAxis:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, angle: float, axis: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> None: ...

    @overload
    def __init__(self, angle: float, axis: object) -> None: ...

    @overload
    def __init__(self, quaternion: Quaternion) -> None: ...

    def Identity(*args, **kwargs): ...

    def angle(self) -> float: ...

    def axis(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def to_rotation_matrix(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    identity = Identity

class SO3:
    def __init__(self) -> None: ...

    def __eq__(self, arg: SO3, /) -> bool: ...

    def __ne__(self, arg: SO3, /) -> bool: ...

    def __mul__(self, arg: SO3, /) -> SO3: ...

    def __str__(self) -> "std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >": ...

    def __repr__(self) -> "std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >": ...

    def set_random(self) -> None: ...

    def is_approx(self, other: SO3, tol: float = ...) -> bool: ...

    def is_identity(self, tol: float = ...) -> bool: ...

    def inverse(self) -> SO3: ...

    def log(self, tol: float = ...) -> SO3Tangent: ...

    def inverse_in_place(self) -> SO3: ...

    def to_matrix(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    Tangent: TypeAlias = SO3Tangent

class SE3:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: SO3, arg1: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> None: ...

    def __eq__(self, arg: SE3, /) -> bool: ...

    def __ne__(self, arg: SE3, /) -> bool: ...

    def __mul__(self, arg: SE3, /) -> SE3: ...

    def __str__(self) -> "std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >": ...

    def __repr__(self) -> "std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >": ...

    def is_approx(self, other: SE3, tol: float = ...) -> bool: ...

    def is_identity(self, tol: float = ...) -> bool: ...

    def inverse(self) -> SE3: ...

    def log(self, tol: float = ...) -> SE3Tangent: ...

    def inverse_in_place(self) -> SE3: ...

    def to_matrix(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]: ...

    Tangent: TypeAlias = SE3Tangent

def rand_so3() -> SO3: ...

def rand_se3() -> SE3: ...

class SO3Tangent:
    def __init__(self) -> None: ...

    @staticmethod
    def zero() -> SO3Tangent: ...

    @staticmethod
    def random() -> SO3Tangent: ...

    def __eq__(self, arg: SO3Tangent, /) -> bool: ...

    def __ne__(self, arg: SO3Tangent, /) -> bool: ...

    def __str__(self) -> "std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >": ...

    def __repr__(self) -> "std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >": ...

    def is_approx(self, other: SO3Tangent, tol: float = ...) -> bool: ...

    def is_zero(self, tol: float = ...) -> bool: ...

    def exp(self, tol: float = ...) -> SO3: ...

class SE3Tangent:
    def __init__(self) -> None: ...

    @staticmethod
    def zero() -> SE3Tangent: ...

    @staticmethod
    def random() -> SE3Tangent: ...

    def __eq__(self, arg: SE3Tangent, /) -> bool: ...

    def __ne__(self, arg: SE3Tangent, /) -> bool: ...

    def __str__(self) -> "std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >": ...

    def __repr__(self) -> "std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >": ...

    def is_approx(self, other: SE3Tangent, tol: float = ...) -> bool: ...

    def is_zero(self, tol: float = ...) -> bool: ...

    def exp(self, tol: float = ...) -> SE3: ...

def rand_so3_tangent() -> SO3Tangent: ...

def rand_se3_tangent() -> SE3Tangent: ...

@overload
def exp(dx: SO3Tangent, tol: float = ...) -> SO3: ...

@overload
def exp(dx: SE3Tangent, tol: float = ...) -> SE3: ...

@overload
def log(x: SO3, tol: float = ...) -> SO3Tangent: ...

@overload
def log(x: SE3, tol: float = ...) -> SE3Tangent: ...

class LcpSolverStatus(enum.Enum):
    SUCCESS = 0

    FAILED = 1

    MAX_ITERATIONS = 2

    NUMERICAL_ERROR = 3

    INVALID_PROBLEM = 4

    DEGENERATE = 5

    NOT_SOLVED = 6

def lcp_solver_status_to_string(status: LcpSolverStatus) -> str: ...

class LcpProblemType(enum.Enum):
    INVALID = 0

    STANDARD = 1

    BOXED = 2

    FRICTION_INDEX = 3

def lcp_problem_type_to_string(type: LcpProblemType) -> str: ...

class LcpResult:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, status: LcpSolverStatus) -> None: ...

    @property
    def status(self) -> LcpSolverStatus: ...

    @status.setter
    def status(self, arg: LcpSolverStatus, /) -> None: ...

    @property
    def iterations(self) -> int: ...

    @iterations.setter
    def iterations(self, arg: int, /) -> None: ...

    @property
    def residual(self) -> float: ...

    @residual.setter
    def residual(self, arg: float, /) -> None: ...

    @property
    def complementarity(self) -> float: ...

    @complementarity.setter
    def complementarity(self, arg: float, /) -> None: ...

    @property
    def validated(self) -> bool: ...

    @validated.setter
    def validated(self, arg: bool, /) -> None: ...

    @property
    def message(self) -> str: ...

    @message.setter
    def message(self, arg: str, /) -> None: ...

    def succeeded(self) -> bool: ...

    def __repr__(self) -> str: ...

class LcpOptions:
    def __init__(self) -> None: ...

    @property
    def max_iterations(self) -> int: ...

    @max_iterations.setter
    def max_iterations(self, arg: int, /) -> None: ...

    @property
    def absolute_tolerance(self) -> float: ...

    @absolute_tolerance.setter
    def absolute_tolerance(self, arg: float, /) -> None: ...

    @property
    def relative_tolerance(self) -> float: ...

    @relative_tolerance.setter
    def relative_tolerance(self, arg: float, /) -> None: ...

    @property
    def complementarity_tolerance(self) -> float: ...

    @complementarity_tolerance.setter
    def complementarity_tolerance(self, arg: float, /) -> None: ...

    @property
    def validate_solution(self) -> bool: ...

    @validate_solution.setter
    def validate_solution(self, arg: bool, /) -> None: ...

    @property
    def relaxation(self) -> float: ...

    @relaxation.setter
    def relaxation(self, arg: float, /) -> None: ...

    @property
    def warm_start(self) -> bool: ...

    @warm_start.setter
    def warm_start(self, arg: bool, /) -> None: ...

    @property
    def early_termination(self) -> bool: ...

    @early_termination.setter
    def early_termination(self, arg: bool, /) -> None: ...

    @staticmethod
    def with_relaxation(relaxation: float, max_iterations: int = ...) -> LcpOptions: ...

    @staticmethod
    def high_accuracy() -> LcpOptions: ...

    @staticmethod
    def real_time() -> LcpOptions: ...

class PgsSolverParameters:
    def __init__(self) -> None: ...

    @property
    def epsilon_for_division(self) -> float: ...

    @epsilon_for_division.setter
    def epsilon_for_division(self, arg: float, /) -> None: ...

    @property
    def randomize_constraint_order(self) -> bool: ...

    @randomize_constraint_order.setter
    def randomize_constraint_order(self, arg: bool, /) -> None: ...

class SymmetricPsorSolverParameters:
    def __init__(self) -> None: ...

    @property
    def epsilon_for_division(self) -> float: ...

    @epsilon_for_division.setter
    def epsilon_for_division(self, arg: float, /) -> None: ...

class JacobiSolverParameters:
    def __init__(self) -> None: ...

    @property
    def epsilon_for_division(self) -> float: ...

    @epsilon_for_division.setter
    def epsilon_for_division(self, arg: float, /) -> None: ...

    @property
    def worker_threads(self) -> int: ...

    @worker_threads.setter
    def worker_threads(self, arg: int, /) -> None: ...

class RedBlackGaussSeidelSolverParameters:
    def __init__(self) -> None: ...

    @property
    def epsilon_for_division(self) -> float: ...

    @epsilon_for_division.setter
    def epsilon_for_division(self, arg: float, /) -> None: ...

    @property
    def worker_threads(self) -> int: ...

    @worker_threads.setter
    def worker_threads(self, arg: int, /) -> None: ...

class BlockedJacobiSolverParameters:
    def __init__(self) -> None: ...

    @property
    def block_sizes(self) -> list[int]: ...

    @block_sizes.setter
    def block_sizes(self, arg: Sequence[int], /) -> None: ...

    @property
    def worker_threads(self) -> int: ...

    @worker_threads.setter
    def worker_threads(self, arg: int, /) -> None: ...

class BgsSolverParameters:
    def __init__(self) -> None: ...

    @property
    def block_sizes(self) -> list[int]: ...

    @block_sizes.setter
    def block_sizes(self, arg: Sequence[int], /) -> None: ...

class NncgSolverParameters:
    def __init__(self) -> None: ...

    @property
    def pgs_iterations(self) -> int: ...

    @pgs_iterations.setter
    def pgs_iterations(self, arg: int, /) -> None: ...

    @property
    def restart_interval(self) -> int: ...

    @restart_interval.setter
    def restart_interval(self, arg: int, /) -> None: ...

    @property
    def restart_threshold(self) -> float: ...

    @restart_threshold.setter
    def restart_threshold(self, arg: float, /) -> None: ...

class SubspaceMinimizationSolverParameters:
    def __init__(self) -> None: ...

    @property
    def pgs_iterations(self) -> int: ...

    @pgs_iterations.setter
    def pgs_iterations(self, arg: int, /) -> None: ...

    @property
    def active_set_tolerance(self) -> float: ...

    @active_set_tolerance.setter
    def active_set_tolerance(self, arg: float, /) -> None: ...

class ApgdSolverParameters:
    def __init__(self) -> None: ...

    @property
    def epsilon_for_division(self) -> float: ...

    @epsilon_for_division.setter
    def epsilon_for_division(self, arg: float, /) -> None: ...

    @property
    def adaptive_restart(self) -> bool: ...

    @adaptive_restart.setter
    def adaptive_restart(self, arg: bool, /) -> None: ...

    @property
    def restart_check_interval(self) -> int: ...

    @restart_check_interval.setter
    def restart_check_interval(self, arg: int, /) -> None: ...

class TgsSolverParameters:
    def __init__(self) -> None: ...

    @property
    def epsilon_for_division(self) -> float: ...

    @epsilon_for_division.setter
    def epsilon_for_division(self, arg: float, /) -> None: ...

class MinimumMapNewtonSolverParameters:
    def __init__(self) -> None: ...

    @property
    def max_line_search_steps(self) -> int: ...

    @max_line_search_steps.setter
    def max_line_search_steps(self, arg: int, /) -> None: ...

    @property
    def step_reduction(self) -> float: ...

    @step_reduction.setter
    def step_reduction(self, arg: float, /) -> None: ...

    @property
    def sufficient_decrease(self) -> float: ...

    @sufficient_decrease.setter
    def sufficient_decrease(self, arg: float, /) -> None: ...

    @property
    def min_step(self) -> float: ...

    @min_step.setter
    def min_step(self, arg: float, /) -> None: ...

    @property
    def max_gradient_descent_warm_start_steps(self) -> int: ...

    @max_gradient_descent_warm_start_steps.setter
    def max_gradient_descent_warm_start_steps(self, arg: int, /) -> None: ...

    @property
    def max_gradient_descent_line_search_steps(self) -> int: ...

    @max_gradient_descent_line_search_steps.setter
    def max_gradient_descent_line_search_steps(self, arg: int, /) -> None: ...

    @property
    def gradient_descent_step_reduction(self) -> float: ...

    @gradient_descent_step_reduction.setter
    def gradient_descent_step_reduction(self, arg: float, /) -> None: ...

    @property
    def gradient_descent_sufficient_decrease(self) -> float: ...

    @gradient_descent_sufficient_decrease.setter
    def gradient_descent_sufficient_decrease(self, arg: float, /) -> None: ...

    @property
    def gradient_descent_min_step(self) -> float: ...

    @gradient_descent_min_step.setter
    def gradient_descent_min_step(self, arg: float, /) -> None: ...

    @property
    def max_pgs_warm_start_iterations(self) -> int: ...

    @max_pgs_warm_start_iterations.setter
    def max_pgs_warm_start_iterations(self, arg: int, /) -> None: ...

    @property
    def pgs_warm_start_relaxation(self) -> float: ...

    @pgs_warm_start_relaxation.setter
    def pgs_warm_start_relaxation(self, arg: float, /) -> None: ...

class FischerBurmeisterNewtonSolverParameters:
    def __init__(self) -> None: ...

    @property
    def smoothing_epsilon(self) -> float: ...

    @smoothing_epsilon.setter
    def smoothing_epsilon(self, arg: float, /) -> None: ...

    @property
    def max_line_search_steps(self) -> int: ...

    @max_line_search_steps.setter
    def max_line_search_steps(self, arg: int, /) -> None: ...

    @property
    def step_reduction(self) -> float: ...

    @step_reduction.setter
    def step_reduction(self, arg: float, /) -> None: ...

    @property
    def sufficient_decrease(self) -> float: ...

    @sufficient_decrease.setter
    def sufficient_decrease(self, arg: float, /) -> None: ...

    @property
    def min_step(self) -> float: ...

    @min_step.setter
    def min_step(self, arg: float, /) -> None: ...

    @property
    def max_gradient_descent_warm_start_steps(self) -> int: ...

    @max_gradient_descent_warm_start_steps.setter
    def max_gradient_descent_warm_start_steps(self, arg: int, /) -> None: ...

    @property
    def max_gradient_descent_line_search_steps(self) -> int: ...

    @max_gradient_descent_line_search_steps.setter
    def max_gradient_descent_line_search_steps(self, arg: int, /) -> None: ...

    @property
    def gradient_descent_step_reduction(self) -> float: ...

    @gradient_descent_step_reduction.setter
    def gradient_descent_step_reduction(self, arg: float, /) -> None: ...

    @property
    def gradient_descent_sufficient_decrease(self) -> float: ...

    @gradient_descent_sufficient_decrease.setter
    def gradient_descent_sufficient_decrease(self, arg: float, /) -> None: ...

    @property
    def gradient_descent_min_step(self) -> float: ...

    @gradient_descent_min_step.setter
    def gradient_descent_min_step(self, arg: float, /) -> None: ...

    @property
    def max_pgs_warm_start_iterations(self) -> int: ...

    @max_pgs_warm_start_iterations.setter
    def max_pgs_warm_start_iterations(self, arg: int, /) -> None: ...

    @property
    def pgs_warm_start_relaxation(self) -> float: ...

    @pgs_warm_start_relaxation.setter
    def pgs_warm_start_relaxation(self, arg: float, /) -> None: ...

class PenalizedFischerBurmeisterNewtonSolverParameters:
    def __init__(self) -> None: ...

    @property
    def smoothing_epsilon(self) -> float: ...

    @smoothing_epsilon.setter
    def smoothing_epsilon(self, arg: float, /) -> None: ...

    @property
    def max_line_search_steps(self) -> int: ...

    @max_line_search_steps.setter
    def max_line_search_steps(self, arg: int, /) -> None: ...

    @property
    def step_reduction(self) -> float: ...

    @step_reduction.setter
    def step_reduction(self, arg: float, /) -> None: ...

    @property
    def sufficient_decrease(self) -> float: ...

    @sufficient_decrease.setter
    def sufficient_decrease(self, arg: float, /) -> None: ...

    @property
    def min_step(self) -> float: ...

    @min_step.setter
    def min_step(self, arg: float, /) -> None: ...

    @property
    def max_gradient_descent_warm_start_steps(self) -> int: ...

    @max_gradient_descent_warm_start_steps.setter
    def max_gradient_descent_warm_start_steps(self, arg: int, /) -> None: ...

    @property
    def max_gradient_descent_line_search_steps(self) -> int: ...

    @max_gradient_descent_line_search_steps.setter
    def max_gradient_descent_line_search_steps(self, arg: int, /) -> None: ...

    @property
    def gradient_descent_step_reduction(self) -> float: ...

    @gradient_descent_step_reduction.setter
    def gradient_descent_step_reduction(self, arg: float, /) -> None: ...

    @property
    def gradient_descent_sufficient_decrease(self) -> float: ...

    @gradient_descent_sufficient_decrease.setter
    def gradient_descent_sufficient_decrease(self, arg: float, /) -> None: ...

    @property
    def gradient_descent_min_step(self) -> float: ...

    @gradient_descent_min_step.setter
    def gradient_descent_min_step(self, arg: float, /) -> None: ...

    @property
    def max_pgs_warm_start_iterations(self) -> int: ...

    @max_pgs_warm_start_iterations.setter
    def max_pgs_warm_start_iterations(self, arg: int, /) -> None: ...

    @property
    def pgs_warm_start_relaxation(self) -> float: ...

    @pgs_warm_start_relaxation.setter
    def pgs_warm_start_relaxation(self, arg: float, /) -> None: ...

class AdmmSolverParameters:
    def __init__(self) -> None: ...

    @property
    def rho_init(self) -> float: ...

    @rho_init.setter
    def rho_init(self, arg: float, /) -> None: ...

    @property
    def mu_prox(self) -> float: ...

    @mu_prox.setter
    def mu_prox(self, arg: float, /) -> None: ...

    @property
    def adaptive_rho_tolerance(self) -> float: ...

    @adaptive_rho_tolerance.setter
    def adaptive_rho_tolerance(self, arg: float, /) -> None: ...

    @property
    def adaptive_rho(self) -> bool: ...

    @adaptive_rho.setter
    def adaptive_rho(self, arg: bool, /) -> None: ...

class SapSolverParameters:
    def __init__(self) -> None: ...

    @property
    def regularization(self) -> float: ...

    @regularization.setter
    def regularization(self, arg: float, /) -> None: ...

    @property
    def armijos_parameter(self) -> float: ...

    @armijos_parameter.setter
    def armijos_parameter(self, arg: float, /) -> None: ...

    @property
    def backtracking_factor(self) -> float: ...

    @backtracking_factor.setter
    def backtracking_factor(self, arg: float, /) -> None: ...

    @property
    def max_line_search_iterations(self) -> int: ...

    @max_line_search_iterations.setter
    def max_line_search_iterations(self, arg: int, /) -> None: ...

class BoxedSemiSmoothNewtonSolverParameters:
    def __init__(self) -> None: ...

    @property
    def max_line_search_steps(self) -> int: ...

    @max_line_search_steps.setter
    def max_line_search_steps(self, arg: int, /) -> None: ...

    @property
    def step_reduction(self) -> float: ...

    @step_reduction.setter
    def step_reduction(self, arg: float, /) -> None: ...

    @property
    def sufficient_decrease(self) -> float: ...

    @sufficient_decrease.setter
    def sufficient_decrease(self, arg: float, /) -> None: ...

    @property
    def min_step(self) -> float: ...

    @min_step.setter
    def min_step(self, arg: float, /) -> None: ...

    @property
    def jacobian_regularization(self) -> float: ...

    @jacobian_regularization.setter
    def jacobian_regularization(self, arg: float, /) -> None: ...

    @property
    def max_pgs_warm_start_iterations(self) -> int: ...

    @max_pgs_warm_start_iterations.setter
    def max_pgs_warm_start_iterations(self, arg: int, /) -> None: ...

    @property
    def pgs_warm_start_relaxation(self) -> float: ...

    @pgs_warm_start_relaxation.setter
    def pgs_warm_start_relaxation(self, arg: float, /) -> None: ...

    @property
    def max_friction_index_exact_solve_dimension(self) -> int: ...

    @max_friction_index_exact_solve_dimension.setter
    def max_friction_index_exact_solve_dimension(self, arg: int, /) -> None: ...

class InteriorPointSolverParameters:
    def __init__(self) -> None: ...

    @property
    def sigma(self) -> float: ...

    @sigma.setter
    def sigma(self, arg: float, /) -> None: ...

    @property
    def step_scale(self) -> float: ...

    @step_scale.setter
    def step_scale(self, arg: float, /) -> None: ...

class MprgpSolverParameters:
    def __init__(self) -> None: ...

    @property
    def symmetry_tolerance(self) -> float: ...

    @symmetry_tolerance.setter
    def symmetry_tolerance(self, arg: float, /) -> None: ...

    @property
    def epsilon_for_division(self) -> float: ...

    @epsilon_for_division.setter
    def epsilon_for_division(self, arg: float, /) -> None: ...

    @property
    def check_positive_definite(self) -> bool: ...

    @check_positive_definite.setter
    def check_positive_definite(self, arg: bool, /) -> None: ...

class ShockPropagationSolverParameters:
    def __init__(self) -> None: ...

    @property
    def block_sizes(self) -> list[int]: ...

    @block_sizes.setter
    def block_sizes(self, arg: Sequence[int], /) -> None: ...

    @property
    def layers(self) -> list[list[int]]: ...

    @layers.setter
    def layers(self, arg: Sequence[Sequence[int]], /) -> None: ...

class LcpProblem:
    @overload
    def __init__(self, A: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]) -> None: ...

    @overload
    def __init__(self, A: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], lo: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], hi: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]) -> None: ...

    @overload
    def __init__(self, A: Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')], b: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], lo: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], hi: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')], findex: Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')]) -> None: ...

    @property
    def A(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    @property
    def b(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @property
    def lo(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @property
    def hi(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @property
    def findex(self) -> Annotated[NDArray[numpy.int32], dict(shape=(None,), order='C')]: ...

    def size(self) -> int: ...

    def empty(self) -> bool: ...

    def is_valid(self) -> bool: ...

    def get_validation_message(self) -> str: ...

    def get_type(self, tolerance: float = ...) -> LcpProblemType: ...

    def is_standard_lcp(self, tolerance: float = ...) -> bool: ...

    def is_boxed_lcp(self) -> bool: ...

    def has_friction_index(self) -> bool: ...

    def get_friction_index_row_count(self) -> int: ...

    def get_friction_index_contact_count(self) -> int: ...

class LcpSolver:
    def solve(self, problem: LcpProblem, initial_guess: Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')] | None = ..., options: LcpOptions | None = ...) -> tuple[LcpResult, Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]]: ...

    def get_name(self) -> str: ...

    def get_category(self) -> str: ...

    def supports_standard_lcp(self) -> bool: ...

    def supports_boxed_lcp(self) -> bool: ...

    def supports_friction_index(self) -> bool: ...

    def supports_problem(self, problem: LcpProblem, standard_tolerance: float | None = ...) -> bool: ...

    @property
    def default_options(self) -> LcpOptions: ...

    @default_options.setter
    def default_options(self, arg: LcpOptions, /) -> None: ...

class DantzigSolver(LcpSolver):
    def __init__(self) -> None: ...

class LemkeSolver(LcpSolver):
    def __init__(self) -> None: ...

class BaraffSolver(LcpSolver):
    def __init__(self) -> None: ...

class DirectSolver(LcpSolver):
    def __init__(self) -> None: ...

class PgsSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> PgsSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: PgsSolverParameters, /) -> None: ...

class SymmetricPsorSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> SymmetricPsorSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: SymmetricPsorSolverParameters, /) -> None: ...

class JacobiSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> JacobiSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: JacobiSolverParameters, /) -> None: ...

class RedBlackGaussSeidelSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> RedBlackGaussSeidelSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: RedBlackGaussSeidelSolverParameters, /) -> None: ...

class BlockedJacobiSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> BlockedJacobiSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: BlockedJacobiSolverParameters, /) -> None: ...

class BgsSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> BgsSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: BgsSolverParameters, /) -> None: ...

class NncgSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> NncgSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: NncgSolverParameters, /) -> None: ...

class SubspaceMinimizationSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> SubspaceMinimizationSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: SubspaceMinimizationSolverParameters, /) -> None: ...

class ApgdSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> ApgdSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: ApgdSolverParameters, /) -> None: ...

class TgsSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> TgsSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: TgsSolverParameters, /) -> None: ...

class MinimumMapNewtonSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> MinimumMapNewtonSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: MinimumMapNewtonSolverParameters, /) -> None: ...

class FischerBurmeisterNewtonSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> FischerBurmeisterNewtonSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: FischerBurmeisterNewtonSolverParameters, /) -> None: ...

class PenalizedFischerBurmeisterNewtonSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> PenalizedFischerBurmeisterNewtonSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: PenalizedFischerBurmeisterNewtonSolverParameters, /) -> None: ...

class BoxedSemiSmoothNewtonSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> BoxedSemiSmoothNewtonSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: BoxedSemiSmoothNewtonSolverParameters, /) -> None: ...

class InteriorPointSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> InteriorPointSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: InteriorPointSolverParameters, /) -> None: ...

class MprgpSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> MprgpSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: MprgpSolverParameters, /) -> None: ...

class ShockPropagationSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> ShockPropagationSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: ShockPropagationSolverParameters, /) -> None: ...

class StaggeringSolver(LcpSolver):
    def __init__(self) -> None: ...

class AdmmSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> AdmmSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: AdmmSolverParameters, /) -> None: ...

class SapSolver(LcpSolver):
    def __init__(self) -> None: ...

    @property
    def parameters(self) -> SapSolverParameters: ...

    @parameters.setter
    def parameters(self, arg: SapSolverParameters, /) -> None: ...

class TriMesh:
    def __init__(self) -> None: ...

    def addVertex(*args, **kwargs) -> Any: ...

    def addTriangle(*args, **kwargs) -> Any: ...

    def addVertexNormal(*args, **kwargs) -> Any: ...

    def reserveVertices(*args, **kwargs) -> Any: ...

    def reserveTriangles(*args, **kwargs) -> Any: ...

    def reserveVertexNormals(*args, **kwargs) -> Any: ...

    def getVertices(*args, **kwargs) -> Any: ...

    def getTriangles(*args, **kwargs) -> Any: ...

    def getVertexNormals(*args, **kwargs) -> Any: ...

    def hasVertexNormals(*args, **kwargs) -> Any: ...

    def computeVertexNormals(*args, **kwargs) -> Any: ...

    def getNumVertices(*args, **kwargs) -> Any: ...

    def getNumTriangles(*args, **kwargs) -> Any: ...

    def clear(self) -> None: ...

    add_triangle = addTriangle

    add_vertex = addVertex

    add_vertex_normal = addVertexNormal

    compute_vertex_normals = computeVertexNormals

    get_num_triangles = getNumTriangles

    get_num_vertices = getNumVertices

    get_triangles = getTriangles

    get_vertex_normals = getVertexNormals

    get_vertices = getVertices

    has_vertex_normals = hasVertexNormals

    reserve_triangles = reserveTriangles

    reserve_vertex_normals = reserveVertexNormals

    reserve_vertices = reserveVertices

euler_xyx_to_matrix = eulerXYXToMatrix

euler_xyz_to_matrix = eulerXYZToMatrix

euler_xzx_to_matrix = eulerXZXToMatrix

euler_xzy_to_matrix = eulerXZYToMatrix

euler_yxy_to_matrix = eulerYXYToMatrix

euler_yxz_to_matrix = eulerYXZToMatrix

euler_yzx_to_matrix = eulerYZXToMatrix

euler_yzy_to_matrix = eulerYZYToMatrix

euler_zxy_to_matrix = eulerZXYToMatrix

euler_zxz_to_matrix = eulerZXZToMatrix

euler_zyx_to_matrix = eulerZYXToMatrix

euler_zyz_to_matrix = eulerZYZToMatrix

exp_angular = expAngular

exp_map = expMap

exp_map_jac = expMapJac

exp_map_rot = expMapRot

exp_to_quat = expToQuat

matrix_to_euler_xyx = matrixToEulerXYX

matrix_to_euler_xyz = matrixToEulerXYZ

matrix_to_euler_xzy = matrixToEulerXZY

matrix_to_euler_yxz = matrixToEulerYXZ

matrix_to_euler_yzx = matrixToEulerYZX

matrix_to_euler_zxy = matrixToEulerZXY

matrix_to_euler_zyx = matrixToEulerZYX

quat_to_exp = quatToExp

verify_rotation = verifyRotation

verify_transform = verifyTransform
