from __future__ import annotations

__all__: list[str] = ["MultiBody", "RigidBody", "World"]


class MultiBody:
    def getName(self) -> str:
        ...

    def setName(self, name: str) -> None:
        ...

    def getLinkCount(self) -> int:
        ...

    def getJointCount(self) -> int:
        ...

    def getDOFCount(self) -> int:
        ...

    def get_name(self) -> str:
        ...

    def set_name(self, name: str) -> None:
        ...

    def get_link_count(self) -> int:
        ...

    def get_joint_count(self) -> int:
        ...

    def get_dof_count(self) -> int:
        ...


class RigidBody:
    def getName(self) -> str:
        ...

    def get_name(self) -> str:
        ...


class World:
    def __init__(self) -> None:
        ...

    def addMultiBody(self, name: str) -> MultiBody:
        ...

    def getMultiBody(self, name: str) -> MultiBody | None:
        ...

    def getMultiBodyCount(self) -> int:
        ...

    def addRigidBody(self, name: str) -> RigidBody:
        ...

    def hasRigidBody(self, name: str) -> bool:
        ...

    def getRigidBodyCount(self) -> int:
        ...

    def isSimulationMode(self) -> bool:
        ...

    def enterSimulationMode(self) -> None:
        ...

    def updateKinematics(self) -> None:
        ...

    def clear(self) -> None:
        ...

    def add_multi_body(self, name: str) -> MultiBody:
        ...

    def get_multi_body(self, name: str) -> MultiBody | None:
        ...

    def get_multi_body_count(self) -> int:
        ...

    def add_rigid_body(self, name: str) -> RigidBody:
        ...

    def has_rigid_body(self, name: str) -> bool:
        ...

    def get_rigid_body_count(self) -> int:
        ...

    def is_simulation_mode(self) -> bool:
        ...

    def enter_simulation_mode(self) -> None:
        ...

    def update_kinematics(self) -> None:
        ...
