from __future__ import annotations

__all__: list[str] = [
    "ActuatorType",
    "ClosureDynamicsPolicy",
    "ClosureKinematicsPolicy",
    "CollisionBody",
    "CollisionShape",
    "CollisionShapeType",
    "Contact",
    "DeformableBody",
    "DeformableBodyOptions",
    "DeformableDirichletBoundaryCondition",
    "DeformableEdge",
    "DeformableMaterialProperties",
    "DeformableNeumannBoundaryCondition",
    "DeformableSurfaceTriangle",
    "DeformableTetrahedron",
    "FixedFrame",
    "Frame",
    "FreeFrame",
    "Joint",
    "JointSpec",
    "JointType",
    "Link",
    "LoopClosure",
    "LoopClosureFamily",
    "LoopClosureResidual",
    "LoopClosureResidualCoordinates",
    "LoopClosureRuntimePolicy",
    "LoopClosureSpec",
    "Multibody",
    "RigidBody",
    "RigidBodyOptions",
    "StateSpace",
    "StateVariable",
    "World",
    "WorldSyncStage",
]


from collections.abc import Sequence
import enum
from typing import Annotated, overload

import numpy
from numpy.typing import NDArray


class JointType(enum.Enum):
    FIXED = 0

    REVOLUTE = 1

    PRISMATIC = 2

    SCREW = 3

    UNIVERSAL = 4

    SPHERICAL = 5

    PLANAR = 6

    FLOATING = 7

    CUSTOM = 8

class ActuatorType(enum.Enum):
    FORCE = 0

    PASSIVE = 1

    SERVO = 2

    VELOCITY = 3

    ACCELERATION = 4

    LOCKED = 5

    MIMIC = 6

class LoopClosureFamily(enum.Enum):
    RIGID = 0

    POINT = 1

    DISTANCE = 2

class LoopClosureResidualCoordinates(enum.Enum):
    WORLD = 0

class WorldSyncStage(enum.Enum):
    KINEMATICS = 0

class CollisionShapeType(enum.Enum):
    SPHERE = 0

    BOX = 1

class CollisionShape:
    @staticmethod
    def sphere(radius: float) -> CollisionShape: ...

    @staticmethod
    def box(half_extents: object) -> CollisionShape: ...

    @property
    def type(self) -> CollisionShapeType: ...

    @property
    def radius(self) -> float: ...

    @property
    def half_extents(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

class ClosureKinematicsPolicy(enum.Enum):
    RESIDUAL_ONLY = 0

    PROJECT = 1

class ClosureDynamicsPolicy(enum.Enum):
    RESIDUAL_ONLY = 0

    SOLVE = 1

class StateVariable:
    @property
    def name(self) -> str: ...

    @property
    def start_index(self) -> int: ...

    @property
    def dimension(self) -> int: ...

    @property
    def lower_bound(self) -> float: ...

    @property
    def upper_bound(self) -> float: ...

    def __repr__(self) -> str: ...

class StateSpace:
    def __init__(self) -> None: ...

    def add_variable(self, name: str, dimension: int, *, lower: float = ..., upper: float = ...) -> StateSpace: ...

    def add_variables(self, names: Sequence[str], *, lower: float = ..., upper: float = ...) -> StateSpace: ...

    def finalize(self) -> None: ...

    def has_variable(self, name: str) -> bool: ...

    def get_variable(self, name: str) -> object: ...

    def get_variable_index(self, name: str) -> object: ...

    @property
    def dimension(self) -> int: ...

    @property
    def num_variables(self) -> int: ...

    @property
    def is_finalized(self) -> bool: ...

    @property
    def variables(self) -> list[StateVariable]: ...

    @property
    def variable_names(self) -> list[str]: ...

    @property
    def lower_bounds(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @property
    def upper_bounds(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    def __repr__(self) -> str: ...

class JointSpec:
    def __init__(self, name: str = ..., type: JointType = JointType.REVOLUTE, axis: object | None = ..., axis2: object | None = ..., transform_from_parent: object | None = ...) -> None: ...

    @property
    def name(self) -> str: ...

    @name.setter
    def name(self, arg: str, /) -> None: ...

    @property
    def type(self) -> JointType: ...

    @type.setter
    def type(self, arg: JointType, /) -> None: ...

    @property
    def axis(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @axis.setter
    def axis(self, arg: object, /) -> None: ...

    @property
    def axis2(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @axis2.setter
    def axis2(self, arg: object, /) -> None: ...

    @property
    def transform_from_parent(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]: ...

    @transform_from_parent.setter
    def transform_from_parent(self, arg: object, /) -> None: ...

    def __repr__(self) -> str: ...

class Frame:
    @staticmethod
    def world() -> Frame: ...

    @overload
    def relative_transform(self, relative_to: object) -> Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]: ...

    @overload
    def relative_transform(self, relative_to: object, expressed_in: object) -> Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]: ...

    def is_same_instance_as(self, other: object) -> bool: ...

    @property
    def name(self) -> str: ...

    @property
    def parent_frame(self) -> Frame: ...

    @parent_frame.setter
    def parent_frame(self, arg: object, /) -> None: ...

    @property
    def local_transform(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]: ...

    @property
    def translation(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @property
    def rotation(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    @property
    def quaternion(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4), order='C')]: ...

    @property
    def transform(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]: ...

    @property
    def is_valid(self) -> bool: ...

    @property
    def is_world(self) -> bool: ...

    def __eq__(self, arg: object, /) -> bool: ...

    def __ne__(self, arg: object, /) -> bool: ...

    def __repr__(self) -> str: ...

class FreeFrame(Frame):
    @property
    def local_transform(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]: ...

    @local_transform.setter
    def local_transform(self, arg: object, /) -> None: ...

    def __repr__(self) -> str: ...

class FixedFrame(Frame):
    @property
    def local_transform(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]: ...

    @local_transform.setter
    def local_transform(self, arg: object, /) -> None: ...

    def __repr__(self) -> str: ...

class Joint:
    @property
    def name(self) -> str: ...

    @property
    def type(self) -> JointType: ...

    @property
    def actuator_type(self) -> ActuatorType: ...

    @actuator_type.setter
    def actuator_type(self, arg: ActuatorType, /) -> None: ...

    @property
    def command_velocity(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @command_velocity.setter
    def command_velocity(self, arg: object, /) -> None: ...

    @property
    def axis(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @property
    def axis2(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @property
    def pitch(self) -> float: ...

    @pitch.setter
    def pitch(self, arg: float, /) -> None: ...

    @property
    def num_dofs(self) -> int: ...

    @property
    def position(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @position.setter
    def position(self, arg: object, /) -> None: ...

    @property
    def velocity(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @velocity.setter
    def velocity(self, arg: object, /) -> None: ...

    @property
    def force(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @force.setter
    def force(self, arg: object, /) -> None: ...

    @property
    def acceleration(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @property
    def spring_stiffness(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @spring_stiffness.setter
    def spring_stiffness(self, arg: object, /) -> None: ...

    @property
    def rest_position(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @rest_position.setter
    def rest_position(self, arg: object, /) -> None: ...

    @property
    def damping_coefficient(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @damping_coefficient.setter
    def damping_coefficient(self, arg: object, /) -> None: ...

    @property
    def armature(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @armature.setter
    def armature(self, arg: object, /) -> None: ...

    @property
    def coulomb_friction(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @coulomb_friction.setter
    def coulomb_friction(self, arg: object, /) -> None: ...

    def set_position_limits(self, lower: object, upper: object) -> None: ...

    @property
    def position_lower_limits(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @property
    def position_upper_limits(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    def set_velocity_limits(self, lower: object, upper: object) -> None: ...

    @property
    def velocity_lower_limits(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @property
    def velocity_upper_limits(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    def set_effort_limits(self, lower: object, upper: object) -> None: ...

    @property
    def effort_lower_limits(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @property
    def effort_upper_limits(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @property
    def parent_link(self) -> Link: ...

    @property
    def child_link(self) -> Link: ...

    @property
    def is_valid(self) -> bool: ...

    def __repr__(self) -> str: ...

class Link(Frame):
    @property
    def name(self) -> str: ...

    @property
    def parent_joint(self) -> Joint: ...

    @property
    def mass(self) -> float: ...

    @mass.setter
    def mass(self, arg: float, /) -> None: ...

    @property
    def inertia(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    @inertia.setter
    def inertia(self, arg: object, /) -> None: ...

    @property
    def center_of_mass(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @center_of_mass.setter
    def center_of_mass(self, arg: object, /) -> None: ...

    @property
    def translation(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @property
    def rotation(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    @property
    def quaternion(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4), order='C')]: ...

    @property
    def transform(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]: ...

    def set_collision_shape(self, shape: CollisionShape) -> None: ...

    @property
    def collision_shape(self) -> CollisionShape | None: ...

    @property
    def has_collision_shape(self) -> bool: ...

    @property
    def is_valid(self) -> bool: ...

    def __repr__(self) -> str: ...

class LoopClosure:
    def compute_residual(self) -> LoopClosureResidual: ...

    @property
    def name(self) -> str: ...

    @property
    def family(self) -> LoopClosureFamily: ...

    @property
    def frame_a(self) -> Frame: ...

    @property
    def frame_b(self) -> Frame: ...

    @property
    def offset_a(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]: ...

    @property
    def offset_b(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]: ...

    @property
    def runtime_policy(self) -> LoopClosureRuntimePolicy: ...

    @runtime_policy.setter
    def runtime_policy(self, arg: LoopClosureRuntimePolicy, /) -> None: ...

    @property
    def enabled(self) -> bool: ...

    @enabled.setter
    def enabled(self, arg: bool, /) -> None: ...

    @property
    def kinematics(self) -> ClosureKinematicsPolicy: ...

    @kinematics.setter
    def kinematics(self, arg: ClosureKinematicsPolicy, /) -> None: ...

    @property
    def dynamics(self) -> ClosureDynamicsPolicy: ...

    @dynamics.setter
    def dynamics(self, arg: ClosureDynamicsPolicy, /) -> None: ...

    @property
    def is_valid(self) -> bool: ...

    def __repr__(self) -> str: ...

class LoopClosureSpec:
    def __init__(self, frame_a: object, frame_b: object, family: LoopClosureFamily = LoopClosureFamily.RIGID, *, offset_a: object | None = ..., offset_b: object | None = ...) -> None: ...

    @property
    def frame_a(self) -> Frame: ...

    @frame_a.setter
    def frame_a(self, arg: object, /) -> None: ...

    @property
    def frame_b(self) -> Frame: ...

    @frame_b.setter
    def frame_b(self, arg: object, /) -> None: ...

    @property
    def family(self) -> LoopClosureFamily: ...

    @family.setter
    def family(self, arg: LoopClosureFamily, /) -> None: ...

    @property
    def offset_a(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]: ...

    @offset_a.setter
    def offset_a(self, arg: object, /) -> None: ...

    @property
    def offset_b(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]: ...

    @offset_b.setter
    def offset_b(self, arg: object, /) -> None: ...

    def __repr__(self) -> str: ...

class LoopClosureRuntimePolicy:
    def __init__(self, enabled: bool = ..., kinematics: ClosureKinematicsPolicy = ClosureKinematicsPolicy.RESIDUAL_ONLY, dynamics: ClosureDynamicsPolicy = ClosureDynamicsPolicy.RESIDUAL_ONLY) -> None: ...

    @property
    def enabled(self) -> bool: ...

    @enabled.setter
    def enabled(self, arg: bool, /) -> None: ...

    @property
    def kinematics(self) -> ClosureKinematicsPolicy: ...

    @kinematics.setter
    def kinematics(self, arg: ClosureKinematicsPolicy, /) -> None: ...

    @property
    def dynamics(self) -> ClosureDynamicsPolicy: ...

    @dynamics.setter
    def dynamics(self, arg: ClosureDynamicsPolicy, /) -> None: ...

    def __repr__(self) -> str: ...

class LoopClosureResidual:
    @property
    def value(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @property
    def norm(self) -> float: ...

    @property
    def enabled(self) -> bool: ...

    @property
    def active(self) -> bool: ...

    @property
    def coordinates(self) -> LoopClosureResidualCoordinates: ...

    @property
    def force_available(self) -> bool: ...

    def __repr__(self) -> str: ...

class Multibody:
    @overload
    def add_link(self, name: str = ...) -> Link: ...

    @overload
    def add_link(self, name: str, *, parent: Link, joint: JointSpec = ...) -> Link: ...

    def get_link(self, name: str) -> object: ...

    def get_joint(self, name: str) -> object: ...

    @property
    def name(self) -> str: ...

    @name.setter
    def name(self, arg: str, /) -> None: ...

    @property
    def num_links(self) -> int: ...

    @property
    def num_joints(self) -> int: ...

    @property
    def num_dofs(self) -> int: ...

    @property
    def links(self) -> list[Link]: ...

    @property
    def joints(self) -> list[Joint]: ...

    @property
    def link_names(self) -> list[str]: ...

    @property
    def joint_names(self) -> list[str]: ...

    @property
    def mass_matrix(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    @property
    def inverse_mass_matrix(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    @property
    def coriolis_forces(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @property
    def gravity_forces(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    @property
    def coriolis_and_gravity_forces(self) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    def compute_inverse_dynamics(self, desired_acceleration: object) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    def compute_impulse_response(self, joint_impulse: object) -> Annotated[NDArray[numpy.float64], dict(shape=(None,), order='C')]: ...

    def get_jacobian(self, link: Link) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    def get_world_jacobian(self, link: Link) -> Annotated[NDArray[numpy.float64], dict(shape=(None, None), order='F')]: ...

    @property
    def is_valid(self) -> bool: ...

    def __repr__(self) -> str: ...

class RigidBody(Frame):
    def apply_force(self, force: object) -> None: ...

    def clear_force(self) -> None: ...

    def apply_torque(self, torque: object) -> None: ...

    def clear_torque(self) -> None: ...

    @property
    def name(self) -> str: ...

    @property
    def translation(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @property
    def rotation(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    @property
    def quaternion(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4), order='C')]: ...

    @property
    def transform(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4, 4), order='F')]: ...

    @transform.setter
    def transform(self, arg: object, /) -> None: ...

    @property
    def linear_velocity(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @linear_velocity.setter
    def linear_velocity(self, arg: object, /) -> None: ...

    @property
    def angular_velocity(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @angular_velocity.setter
    def angular_velocity(self, arg: object, /) -> None: ...

    @property
    def mass(self) -> float: ...

    @mass.setter
    def mass(self, arg: float, /) -> None: ...

    @property
    def inertia(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    @inertia.setter
    def inertia(self, arg: object, /) -> None: ...

    @property
    def force(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @force.setter
    def force(self, arg: object, /) -> None: ...

    @property
    def torque(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @torque.setter
    def torque(self, arg: object, /) -> None: ...

    @property
    def is_static(self) -> bool: ...

    @is_static.setter
    def is_static(self, arg: bool, /) -> None: ...

    @property
    def restitution(self) -> float: ...

    @restitution.setter
    def restitution(self, arg: float, /) -> None: ...

    @property
    def friction(self) -> float: ...

    @friction.setter
    def friction(self, arg: float, /) -> None: ...

    def set_collision_shape(self, shape: CollisionShape) -> None: ...

    @property
    def is_deformable_surface_ccd_obstacle(self) -> bool: ...

    @is_deformable_surface_ccd_obstacle.setter
    def is_deformable_surface_ccd_obstacle(self, arg: bool, /) -> None: ...

    @property
    def collision_shape(self) -> CollisionShape | None: ...

    @property
    def has_collision_shape(self) -> bool: ...

    @property
    def linear_momentum(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @property
    def angular_momentum(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @property
    def kinetic_energy(self) -> float: ...

    @property
    def potential_energy(self) -> float: ...

    def __repr__(self) -> str: ...

class RigidBodyOptions:
    def __init__(self, mass: float = ..., position: object | None = ..., orientation: object | None = ..., linear_velocity: object | None = ..., angular_velocity: object | None = ..., inertia: object | None = ...) -> None: ...

    @property
    def mass(self) -> float: ...

    @mass.setter
    def mass(self, arg: float, /) -> None: ...

    @property
    def position(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @position.setter
    def position(self, arg: object, /) -> None: ...

    @property
    def orientation(self) -> Annotated[NDArray[numpy.float64], dict(shape=(4), order='C')]: ...

    @orientation.setter
    def orientation(self, arg: object, /) -> None: ...

    @property
    def linear_velocity(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @linear_velocity.setter
    def linear_velocity(self, arg: object, /) -> None: ...

    @property
    def angular_velocity(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @angular_velocity.setter
    def angular_velocity(self, arg: object, /) -> None: ...

    @property
    def inertia(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3, 3), order='F')]: ...

    @inertia.setter
    def inertia(self, arg: object, /) -> None: ...

    @property
    def is_static(self) -> bool: ...

    @is_static.setter
    def is_static(self, arg: bool, /) -> None: ...

    def __repr__(self) -> str: ...

class CollisionBody:
    @property
    def name(self) -> str: ...

    @property
    def is_rigid_body(self) -> bool: ...

    @property
    def is_link(self) -> bool: ...

    @property
    def is_valid(self) -> bool: ...

    def as_rigid_body(self) -> object: ...

    def as_link(self) -> object: ...

class Contact:
    @property
    def body_a(self) -> CollisionBody: ...

    @property
    def body_b(self) -> CollisionBody: ...

    @property
    def point(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @property
    def normal(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @property
    def depth(self) -> float: ...

class DeformableMaterialProperties:
    def __init__(self) -> None: ...

    @property
    def density(self) -> float: ...

    @density.setter
    def density(self, arg: float, /) -> None: ...

    @property
    def youngs_modulus(self) -> float: ...

    @youngs_modulus.setter
    def youngs_modulus(self, arg: float, /) -> None: ...

    @property
    def poisson_ratio(self) -> float: ...

    @poisson_ratio.setter
    def poisson_ratio(self, arg: float, /) -> None: ...

    @property
    def friction_coefficient(self) -> float: ...

    @friction_coefficient.setter
    def friction_coefficient(self, arg: float, /) -> None: ...

class DeformableEdge:
    def __init__(self, node_a: int = ..., node_b: int = ..., rest_length: float = ...) -> None: ...

    @property
    def node_a(self) -> int: ...

    @node_a.setter
    def node_a(self, arg: int, /) -> None: ...

    @property
    def node_b(self) -> int: ...

    @node_b.setter
    def node_b(self, arg: int, /) -> None: ...

    @property
    def rest_length(self) -> float: ...

    @rest_length.setter
    def rest_length(self, arg: float, /) -> None: ...

class DeformableSurfaceTriangle:
    def __init__(self, node_a: int = ..., node_b: int = ..., node_c: int = ...) -> None: ...

    @property
    def node_a(self) -> int: ...

    @node_a.setter
    def node_a(self, arg: int, /) -> None: ...

    @property
    def node_b(self) -> int: ...

    @node_b.setter
    def node_b(self, arg: int, /) -> None: ...

    @property
    def node_c(self) -> int: ...

    @node_c.setter
    def node_c(self, arg: int, /) -> None: ...

class DeformableTetrahedron:
    def __init__(self, node_a: int = ..., node_b: int = ..., node_c: int = ..., node_d: int = ...) -> None: ...

    @property
    def node_a(self) -> int: ...

    @node_a.setter
    def node_a(self, arg: int, /) -> None: ...

    @property
    def node_b(self) -> int: ...

    @node_b.setter
    def node_b(self, arg: int, /) -> None: ...

    @property
    def node_c(self) -> int: ...

    @node_c.setter
    def node_c(self, arg: int, /) -> None: ...

    @property
    def node_d(self) -> int: ...

    @node_d.setter
    def node_d(self, arg: int, /) -> None: ...

class DeformableDirichletBoundaryCondition:
    def __init__(self) -> None: ...

    @property
    def nodes(self) -> list[int]: ...

    @nodes.setter
    def nodes(self, arg: Sequence[int], /) -> None: ...

    @property
    def linear_velocity(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @linear_velocity.setter
    def linear_velocity(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> None: ...

    @property
    def angular_velocity(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @angular_velocity.setter
    def angular_velocity(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> None: ...

    @property
    def center(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @center.setter
    def center(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> None: ...

    @property
    def start_time(self) -> float: ...

    @start_time.setter
    def start_time(self, arg: float, /) -> None: ...

    @property
    def end_time(self) -> float: ...

    @end_time.setter
    def end_time(self, arg: float, /) -> None: ...

class DeformableNeumannBoundaryCondition:
    def __init__(self) -> None: ...

    @property
    def nodes(self) -> list[int]: ...

    @nodes.setter
    def nodes(self, arg: Sequence[int], /) -> None: ...

    @property
    def acceleration(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @acceleration.setter
    def acceleration(self, arg: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], /) -> None: ...

    @property
    def start_time(self) -> float: ...

    @start_time.setter
    def start_time(self, arg: float, /) -> None: ...

    @property
    def end_time(self) -> float: ...

    @end_time.setter
    def end_time(self, arg: float, /) -> None: ...

class DeformableBodyOptions:
    def __init__(self) -> None: ...

    @property
    def positions(self) -> list[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]]: ...

    @positions.setter
    def positions(self, arg: Sequence[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], /) -> None: ...

    @property
    def velocities(self) -> list[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]]: ...

    @velocities.setter
    def velocities(self, arg: Sequence[Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]], /) -> None: ...

    @property
    def masses(self) -> list[float]: ...

    @masses.setter
    def masses(self, arg: Sequence[float], /) -> None: ...

    @property
    def edges(self) -> list[DeformableEdge]: ...

    @edges.setter
    def edges(self, arg: Sequence[DeformableEdge], /) -> None: ...

    @property
    def surface_triangles(self) -> list[DeformableSurfaceTriangle]: ...

    @surface_triangles.setter
    def surface_triangles(self, arg: Sequence[DeformableSurfaceTriangle], /) -> None: ...

    @property
    def tetrahedra(self) -> list[DeformableTetrahedron]: ...

    @tetrahedra.setter
    def tetrahedra(self, arg: Sequence[DeformableTetrahedron], /) -> None: ...

    @property
    def dirichlet_boundary_conditions(self) -> list[DeformableDirichletBoundaryCondition]: ...

    @dirichlet_boundary_conditions.setter
    def dirichlet_boundary_conditions(self, arg: Sequence[DeformableDirichletBoundaryCondition], /) -> None: ...

    @property
    def neumann_boundary_conditions(self) -> list[DeformableNeumannBoundaryCondition]: ...

    @neumann_boundary_conditions.setter
    def neumann_boundary_conditions(self, arg: Sequence[DeformableNeumannBoundaryCondition], /) -> None: ...

    @property
    def fixed_nodes(self) -> list[int]: ...

    @fixed_nodes.setter
    def fixed_nodes(self, arg: Sequence[int], /) -> None: ...

    @property
    def edge_stiffness(self) -> float: ...

    @edge_stiffness.setter
    def edge_stiffness(self, arg: float, /) -> None: ...

    @property
    def damping(self) -> float: ...

    @damping.setter
    def damping(self, arg: float, /) -> None: ...

    @property
    def material(self) -> DeformableMaterialProperties: ...

    @material.setter
    def material(self, arg: DeformableMaterialProperties, /) -> None: ...

class DeformableBody:
    @property
    def is_valid(self) -> bool: ...

    @property
    def name(self) -> str: ...

    @property
    def node_count(self) -> int: ...

    @property
    def edge_count(self) -> int: ...

    @property
    def surface_triangle_count(self) -> int: ...

    @property
    def tetrahedron_count(self) -> int: ...

    def node_position(self, node: int) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def set_node_position(self, node: int, position: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> None: ...

    def node_velocity(self, node: int) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    def set_node_velocity(self, node: int, velocity: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> None: ...

    def node_mass(self, node: int) -> float: ...

    def is_fixed_node(self, node: int) -> bool: ...

    def edge(self, edge: int) -> DeformableEdge: ...

    def surface_triangle(self, triangle: int) -> DeformableSurfaceTriangle: ...

    def tetrahedron(self, tetrahedron: int) -> DeformableTetrahedron: ...

    def tetrahedron_rest_volume(self, tetrahedron: int) -> float: ...

    @property
    def material_properties(self) -> DeformableMaterialProperties: ...

class World:
    def __init__(self, time_step: float = ...) -> None: ...

    def add_free_frame(self, name: str = ..., *, parent: object | None = ...) -> FreeFrame: ...

    def add_fixed_frame(self, name: str, parent: object, offset: object | None = ...) -> FixedFrame: ...

    def add_multibody(self, name: str) -> Multibody: ...

    def get_multibody(self, name: str) -> object: ...

    def has_multibody(self, name: str) -> bool: ...

    def add_deformable_body(self, name: str, options: DeformableBodyOptions) -> DeformableBody: ...

    def get_deformable_body(self, name: str) -> object: ...

    def has_deformable_body(self, name: str) -> bool: ...

    def get_deformable_body_count(self) -> int: ...

    @overload
    def add_loop_closure(self, spec: LoopClosureSpec, *, name: object | None = ...) -> LoopClosure: ...

    @overload
    def add_loop_closure(self, name: object, spec: LoopClosureSpec) -> LoopClosure: ...

    @overload
    def add_loop_closure(self, name: object | None = ..., *, frame_a: object, frame_b: object, family: LoopClosureFamily = LoopClosureFamily.RIGID, offset_a: object | None = ..., offset_b: object | None = ...) -> LoopClosure: ...

    def has_loop_closure(self, name: str) -> bool: ...

    def get_loop_closure(self, name: str) -> object: ...

    def add_rigid_body(self, name: str, options: RigidBodyOptions = ..., *, mass: object | None = ..., position: object | None = ..., orientation: object | None = ..., linear_velocity: object | None = ..., angular_velocity: object | None = ..., inertia: object | None = ...) -> RigidBody: ...

    def has_rigid_body(self, name: str) -> bool: ...

    def get_rigid_body(self, name: str) -> object: ...

    @property
    def is_simulation_mode(self) -> bool: ...

    def enter_simulation_mode(self) -> None: ...

    def update_kinematics(self) -> None: ...

    def sync(self, stage: WorldSyncStage = WorldSyncStage.KINEMATICS) -> None: ...

    def step(self, n: int = ...) -> None: ...

    @property
    def time_step(self) -> float: ...

    @time_step.setter
    def time_step(self, arg: float, /) -> None: ...

    @property
    def time(self) -> float: ...

    @time.setter
    def time(self, arg: float, /) -> None: ...

    @property
    def gravity(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

    @gravity.setter
    def gravity(self, arg: object, /) -> None: ...

    @property
    def frame(self) -> int: ...

    @property
    def num_multibodies(self) -> int: ...

    @property
    def num_loop_closures(self) -> int: ...

    @property
    def num_rigid_bodies(self) -> int: ...

    def collide(self) -> list[Contact]: ...

    def clear(self) -> None: ...

    def __repr__(self) -> str: ...
