if(NOT DEFINED INPUT)
  message(FATAL_ERROR "INPUT is required")
endif()
if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "OUTPUT is required")
endif()
if(NOT DEFINED SYMBOL)
  message(FATAL_ERROR "SYMBOL is required")
endif()
if(NOT DEFINED NAMESPACE)
  set(NAMESPACE "dart::examples")
endif()

file(READ "${INPUT}" _hex HEX)
string(REGEX MATCHALL ".." _bytes "${_hex}")

set(_content "#pragma once\n\n#include <cstddef>\n#include <cstdint>\n\nnamespace ${NAMESPACE} {\n\ninline constexpr std::uint8_t ${SYMBOL}[] = {\n")
set(_column 0)
foreach(_byte IN LISTS _bytes)
  if(_column EQUAL 0)
    string(APPEND _content "  ")
  endif()
  string(APPEND _content "0x${_byte}, ")
  math(EXPR _column "(${_column} + 1) % 12")
  if(_column EQUAL 0)
    string(APPEND _content "\n")
  endif()
endforeach()
if(NOT _column EQUAL 0)
  string(APPEND _content "\n")
endif()
string(APPEND _content "};\ninline constexpr std::size_t ${SYMBOL}Size = sizeof(${SYMBOL});\n\n} // namespace ${NAMESPACE}\n")

file(WRITE "${OUTPUT}" "${_content}")
