/*
 * Copyright (c) 2011, The DART development contributors
 * All rights reserved.
 *
 * The list of contributors can be found at:
 *   https://github.com/dartsim/dart/blob/main/LICENSE
 *
 * This file is provided under the following "BSD-style" License:
 *   Redistribution and use in source and binary forms, with or
 *   without modification, are permitted provided that the following
 *   conditions are met:
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
 *   CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 *   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 *   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *   DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 *   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 *   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 *   AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *   LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *   ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *   POSSIBILITY OF SUCH DAMAGE.
 */

// Ported from examples/contact_inverse_dynamics: a kinematic squat cycle for
// fullbody1.skel (60 Catmull-Rom keyframes generated by hierarchical
// whole-body IK) solved every frame for contact-consistent joint torques via
// dart::dynamics::ContactInverseDynamics, with force arrows at the four foot
// contacts and ImGui plots of the vertical GRF and three leg torques.
//
// Deviations from the original: fullbody1.skel is authored Y-up; reoriented
// to the host's Z-up convention via ZUp.hpp, like every other B3
// fullbody1.skel scene. The squat depth is applied along the pelvis target's
// Z translation (was Y in the original) because ZUp.hpp maps the source
// world's +Y (up) onto +Z; the up direction used for contact normals is
// derived from gravity (already rotated by ZUp.hpp), so it needs no such
// change. The world is never physically stepped, exactly as in the original
// (all motion is kinematic, driven by an internal clock); since this host
// always calls World::step() for the Step button, --cycle-scenes, and
// --headless capture, this scene's preStep/postStep hooks are left empty and
// the entire per-frame update (advance the clock, evaluate the spline,
// re-solve contacts, update the arrows) runs at the top of renderPanel
// instead -- called once per rendered frame regardless of pause state, the
// same cadence the original's customPreRefresh had (see TinkertoyScene.cpp's
// file comment for the same pattern) -- so the kinematic pose this renders is
// always correct by the time a frame is actually drawn (including the few
// frames rendered before a --headless screenshot), even though raw
// world-stepping during Step/cycle-scenes/headless has no effect on it either
// way. The original's atomic-flag-deferred keyframe regeneration existed to
// keep an ImGui draw-thread callback from touching the skeleton directly;
// this host is single-threaded end to end (no separate draw thread), so
// regeneration runs synchronously from the panel callback instead. The
// original's --frames/--screenshot console-capture mode and --gui-scale flag
// are dropped in favor of the host's generic --cycle-scenes/--headless/
// --gui-scale equivalents.

#include "Scenes.hpp"
#include "ZUp.hpp"

#include <dart/gui/osg/osg.hpp>

#include <dart/utils/utils.hpp>

#include <dart/dart.hpp>

#include <algorithm>
#include <array>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

#include <cmath>

namespace dart_demos {

namespace {

using dart::dynamics::BodyNode;
using dart::dynamics::SkeletonPtr;
using dart::simulation::WorldPtr;

//==============================================================================
/// Per-instance state captured by this scene's renderPanel/onActivate
/// lambdas. Everything here mirrors the original's
/// ContactInverseDynamicsWorldNode + ContactInverseDynamicsWidget.
struct ContactIdState
{
  WorldPtr world;
  SkeletonPtr biped;
  std::unique_ptr<dart::dynamics::ContactInverseDynamics> solver;

  BodyNode* leftHeel = nullptr;
  BodyNode* leftToe = nullptr;
  BodyNode* rightHeel = nullptr;
  BodyNode* rightToe = nullptr;

  std::vector<dart::dynamics::SimpleFramePtr> contactFrames;
  std::vector<std::shared_ptr<dart::dynamics::ArrowShape>> arrows;

  std::vector<Eigen::VectorXd> keyframes;
  Eigen::VectorXd initialPositions;

  std::vector<std::string> torqueNames;
  std::vector<std::size_t> torqueDofs;

  double time = 0.0;

  // Panel-owned controls (ImGuiWidget state in the original).
  bool playing = true;
  float playbackSpeed = 1.0f;
  float squatDepth = 0.15f;
  float frictionCoeff = 0.8f;
  float forceScale = 0.002f;
  // Set when the Squat Depth slider is released or Regenerate is pressed;
  // consumed at the top of the next updateFrame() (see the comment there).
  bool regenerateRequested = false;

  // Status readout.
  bool feasible = true;
  double residualNorm = 0.0;
  std::vector<Eigen::Vector3d> contactForces;
  double totalVerticalForce = 0.0;

  std::vector<float> plotSamples = std::vector<float>(240, 0.0f);
  std::vector<std::vector<float>> torquePlots
      = std::vector<std::vector<float>>(3, std::vector<float>(240, 0.0f));
  std::size_t sampleIndex = 0;
};

//==============================================================================
void findTorqueDofs(ContactIdState& state)
{
  state.torqueNames.clear();
  state.torqueDofs.clear();

  static const char* const candidates[]
      = {"j_thigh_left_z",
         "j_shin_left",
         "j_heel_left_1",
         "j_thigh_right_z",
         "j_shin_right",
         "j_heel_right_1"};

  for (const char* name : candidates) {
    auto* dof = state.biped->getDof(name);
    if (dof && state.torqueNames.size() < 3) {
      state.torqueNames.emplace_back(name);
      state.torqueDofs.push_back(dof->getIndexInSkeleton());
    }
  }
}

//==============================================================================
void generateSquatKeyframes(ContactIdState& state, double depth)
{
  state.biped->setPositions(state.initialPositions);

  constexpr std::size_t numKeyframes = 60;
  state.keyframes.clear();
  state.keyframes.reserve(numKeyframes);

  auto leftHeelIK = state.leftHeel->getIK(true);
  auto rightHeelIK = state.rightHeel->getIK(true);

  auto leftHeelTarget = std::make_shared<dart::dynamics::SimpleFrame>(
      dart::dynamics::Frame::World(),
      "leftHeelTarget",
      state.leftHeel->getWorldTransform());
  auto rightHeelTarget = std::make_shared<dart::dynamics::SimpleFrame>(
      dart::dynamics::Frame::World(),
      "rightHeelTarget",
      state.rightHeel->getWorldTransform());

  leftHeelIK->setTarget(leftHeelTarget);
  leftHeelIK->setHierarchyLevel(0);
  rightHeelIK->setTarget(rightHeelTarget);
  rightHeelIK->setHierarchyLevel(0);

  auto* pelvis = state.biped->getBodyNode(0);
  auto pelvisIK = pelvis->getIK(true);
  auto pelvisTarget = std::make_shared<dart::dynamics::SimpleFrame>(
      dart::dynamics::Frame::World(),
      "pelvisTarget",
      pelvis->getWorldTransform());
  pelvisIK->setTarget(pelvisTarget);
  pelvisIK->setHierarchyLevel(1);

  const Eigen::Isometry3d pelvisInitial = pelvis->getWorldTransform();

  auto wbIK = state.biped->getIK(true);
  if (auto solver = wbIK->getSolver()) {
    if (auto gd
        = std::dynamic_pointer_cast<dart::optimizer::GradientDescentSolver>(
            solver))
      gd->setNumMaxIterations(200);
  }

  for (std::size_t i = 0; i < numKeyframes; ++i) {
    const double phase
        = static_cast<double>(i) / static_cast<double>(numKeyframes);
    const double offset
        = depth * 0.5
          * (1.0 - std::cos(2.0 * dart::math::constantsd::pi() * phase));

    Eigen::Isometry3d pelvisTf = pelvisInitial;
    // Z is "up" in this host's reoriented world (was Y in the original
    // Y-up asset) -- see the file comment.
    pelvisTf.translation()[2] -= offset;
    pelvisTarget->setTransform(pelvisTf);

    wbIK->solveAndApply(true);
    state.keyframes.push_back(state.biped->getPositions());

    if (i == 0) {
      if (auto solver = wbIK->getSolver()) {
        if (auto gd
            = std::dynamic_pointer_cast<dart::optimizer::GradientDescentSolver>(
                solver))
          gd->setNumMaxIterations(50);
      }
    }
  }

  state.biped->setPositions(state.initialPositions);
}

//==============================================================================
Eigen::VectorXd catmullRomInterpolate(const ContactIdState& state, double t)
{
  if (state.keyframes.empty())
    return state.biped->getPositions();

  const std::size_t n = state.keyframes.size();
  const double scaledT = t * static_cast<double>(n);
  const std::size_t i1 = static_cast<std::size_t>(scaledT) % n;
  const double u = scaledT - std::floor(scaledT);

  const std::size_t i0 = (i1 + n - 1) % n;
  const std::size_t i2 = (i1 + 1) % n;
  const std::size_t i3 = (i1 + 2) % n;

  const auto& p0 = state.keyframes[i0];
  const auto& p1 = state.keyframes[i1];
  const auto& p2 = state.keyframes[i2];
  const auto& p3 = state.keyframes[i3];

  const double u2 = u * u;
  const double u3 = u2 * u;

  return 0.5
         * ((-p0 + 3.0 * p1 - 3.0 * p2 + p3) * u3
            + (2.0 * p0 - 5.0 * p1 + 4.0 * p2 - p3) * u2 + (-p0 + p2) * u
            + 2.0 * p1);
}

//==============================================================================
Eigen::VectorXd catmullRomVelocity(const ContactIdState& state, double t)
{
  if (state.keyframes.empty())
    return Eigen::VectorXd::Zero(state.biped->getNumDofs());

  const std::size_t n = state.keyframes.size();
  const double scaledT = t * static_cast<double>(n);
  const std::size_t i1 = static_cast<std::size_t>(scaledT) % n;
  const double u = scaledT - std::floor(scaledT);

  const std::size_t i0 = (i1 + n - 1) % n;
  const std::size_t i2 = (i1 + 1) % n;
  const std::size_t i3 = (i1 + 2) % n;

  const auto& p0 = state.keyframes[i0];
  const auto& p1 = state.keyframes[i1];
  const auto& p2 = state.keyframes[i2];
  const auto& p3 = state.keyframes[i3];

  const double u2 = u * u;

  return 0.5 * static_cast<double>(n)
         * ((3.0 * (-p0 + 3.0 * p1 - 3.0 * p2 + p3)) * u2
            + (2.0 * (2.0 * p0 - 5.0 * p1 + 4.0 * p2 - p3)) * u + (-p0 + p2));
}

//==============================================================================
Eigen::VectorXd catmullRomAcceleration(const ContactIdState& state, double t)
{
  if (state.keyframes.empty())
    return Eigen::VectorXd::Zero(state.biped->getNumDofs());

  const std::size_t n = state.keyframes.size();
  const double scaledT = t * static_cast<double>(n);
  const std::size_t i1 = static_cast<std::size_t>(scaledT) % n;
  const double u = scaledT - std::floor(scaledT);

  const std::size_t i0 = (i1 + n - 1) % n;
  const std::size_t i2 = (i1 + 1) % n;
  const std::size_t i3 = (i1 + 2) % n;

  const auto& p0 = state.keyframes[i0];
  const auto& p1 = state.keyframes[i1];
  const auto& p2 = state.keyframes[i2];
  const auto& p3 = state.keyframes[i3];

  const double nSq = static_cast<double>(n * n);

  return 0.5 * nSq
         * ((6.0 * (-p0 + 3.0 * p1 - 3.0 * p2 + p3)) * u
            + 2.0 * (2.0 * p0 - 5.0 * p1 + 4.0 * p2 - p3));
}

//==============================================================================
/// The per-frame update, ported from customPreRefresh (see the file comment
/// on why it runs from renderPanel here instead).
void updateFrame(ContactIdState& state)
{
  // Consume a deferred keyframe-regeneration request at the top of the frame,
  // before the spline is evaluated below, so the pose drawn this frame comes
  // from the fresh keyframes rather than popping to initialPositions for one
  // frame (mirrors the original's deferred mRegenerateRequested).
  if (state.regenerateRequested) {
    generateSquatKeyframes(state, state.squatDepth);
    state.regenerateRequested = false;
  }

  constexpr double cycleDuration = 3.0;
  if (state.playing)
    state.time += 1.0 / 60.0 * static_cast<double>(state.playbackSpeed);

  const double phase = std::fmod(state.time, cycleDuration) / cycleDuration;
  const double phaseRate
      = state.playing ? static_cast<double>(state.playbackSpeed) / cycleDuration
                      : 0.0;

  const Eigen::VectorXd q = catmullRomInterpolate(state, phase);
  const Eigen::VectorXd dq = catmullRomVelocity(state, phase) * phaseRate;
  const Eigen::VectorXd ddq
      = catmullRomAcceleration(state, phase) * phaseRate * phaseRate;

  state.biped->setPositions(q);
  state.biped->setVelocities(dq);
  state.biped->setAccelerations(ddq);

  const Eigen::Vector3d upDir = -state.world->getGravity().normalized();

  std::vector<dart::dynamics::ContactInverseDynamics::Contact> contacts;
  const std::array<BodyNode*, 4> contactBodies
      = {state.leftHeel, state.leftToe, state.rightHeel, state.rightToe};

  for (auto* body : contactBodies) {
    dart::dynamics::ContactInverseDynamics::Contact contact;
    contact.bodyNode = body;
    contact.localOffset = Eigen::Vector3d::Zero();
    contact.normal = upDir;
    contact.frictionCoeff = state.frictionCoeff;
    contact.numBasis = 8;
    contacts.push_back(contact);
  }

  state.solver->setContacts(contacts);
  const auto result = state.solver->compute();

  state.feasible = result.feasible;
  state.residualNorm = result.unactuatedResidual.lpNorm<Eigen::Infinity>();
  state.contactForces = result.contactForces;

  state.totalVerticalForce = 0.0;
  for (const auto& f : state.contactForces)
    state.totalVerticalForce += f.dot(upDir);
  state.plotSamples[state.sampleIndex]
      = static_cast<float>(state.totalVerticalForce);

  for (std::size_t i = 0;
       i < state.torqueDofs.size() && i < state.torquePlots.size();
       ++i) {
    if (state.torqueDofs[i]
        < static_cast<std::size_t>(result.jointForces.size()))
      state.torquePlots[i][state.sampleIndex]
          = static_cast<float>(result.jointForces[state.torqueDofs[i]]);
  }
  state.sampleIndex = (state.sampleIndex + 1) % state.plotSamples.size();

  for (std::size_t i = 0;
       i < result.contactForces.size() && i < state.contactFrames.size();
       ++i) {
    auto* visual = state.contactFrames[i]->getVisualAspect(true);
    const Eigen::Vector3d force = result.contactForces[i];
    if (force.norm() < 1e-8) {
      visual->setHidden(true);
      continue;
    }
    visual->setHidden(false);

    const Eigen::Vector3d worldPos
        = contactBodies[i]->getWorldTransform() * contacts[i].localOffset;
    const Eigen::Vector3d headPos = worldPos + state.forceScale * force;
    state.arrows[i]->setPositions(worldPos, headPos);

    const Eigen::Vector4d color = result.feasible
                                      ? Eigen::Vector4d(0.0, 1.0, 0.0, 1.0)
                                      : Eigen::Vector4d(1.0, 0.0, 0.0, 1.0);
    state.arrows[i]->notifyColorUpdated(color);
  }
}

} // namespace

//==============================================================================
DemoScene makeContactInverseDynamicsScene()
{
  DemoScene scene;
  scene.id = "contact_inverse_dynamics";
  scene.title = "Contact Inverse Dynamics";
  scene.category = "Control & IK";
  scene.summary
      = "Kinematic squat replay solved for contact-consistent joint torques.";

  scene.factory = [] {
    auto world = dart::utils::SkelParser::readWorld(
        "dart://sample/skel/fullbody1.skel");
    if (!world)
      throw std::runtime_error(
          "failed to load dart://sample/skel/fullbody1.skel");
    reorientWorldToZUp(world);

    auto biped = world->getSkeleton("fullbody1");
    if (!biped)
      throw std::runtime_error("fullbody1.skel: missing skeleton 'fullbody1'");

    const auto setDofPosition = [&](const char* name, double position) {
      if (auto* dof = biped->getDof(name))
        dof->setPosition(position);
    };
    setDofPosition("j_pelvis_rot_y", -0.20);
    setDofPosition("j_thigh_left_z", 0.15);
    setDofPosition("j_shin_left", -0.40);
    setDofPosition("j_heel_left_1", 0.25);
    setDofPosition("j_thigh_right_z", 0.15);
    setDofPosition("j_shin_right", -0.40);
    setDofPosition("j_heel_right_1", 0.25);
    setDofPosition("j_abdomen_2", 0.00);

    auto state = std::make_shared<ContactIdState>();
    state->world = world;
    state->biped = biped;
    state->solver
        = std::make_unique<dart::dynamics::ContactInverseDynamics>(biped);
    // A stronger-than-default regularization keeps the (statically
    // indeterminate) force distribution even and steady across frames; the
    // residual tolerance is widened to match the equality bias it introduces.
    state->solver->setRegularization(1e-4);
    state->solver->setResidualTolerance(1e-4);

    state->leftHeel = biped->getBodyNode("h_heel_left");
    state->leftToe = biped->getBodyNode("h_toe_left");
    state->rightHeel = biped->getBodyNode("h_heel_right");
    state->rightToe = biped->getBodyNode("h_toe_right");
    if (!state->leftHeel || !state->leftToe || !state->rightHeel
        || !state->rightToe)
      throw std::runtime_error(
          "fullbody1.skel: missing one or more foot body nodes");

    for (std::size_t i = 0; i < 4; ++i) {
      auto frame = std::make_shared<dart::dynamics::SimpleFrame>(
          dart::dynamics::Frame::World());
      state->contactFrames.push_back(frame);
      world->addSimpleFrame(frame);

      auto arrow = std::make_shared<dart::dynamics::ArrowShape>(
          Eigen::Vector3d::Zero(),
          Eigen::Vector3d::UnitZ() * 0.1,
          dart::dynamics::ArrowShape::Properties(0.01, 2.0, 0.15),
          Eigen::Vector4d(0.0, 1.0, 0.0, 1.0));
      state->arrows.push_back(arrow);
      frame->setShape(arrow);
      frame->getVisualAspect(true);
    }

    findTorqueDofs(*state);
    state->initialPositions = biped->getPositions();
    generateSquatKeyframes(*state, 0.15);

    DemoSceneSetup setup;
    setup.world = world;
    setup.cameraHome = CameraHome{
        ::osg::Vec3d(3.0, -3.0, 1.5),
        ::osg::Vec3d(0.0, 0.0, 0.0),
        ::osg::Vec3d(0.0, 0.0, 1.0)};

    setup.renderPanel = [state] {
      updateFrame(*state);

      if (ImGui::CollapsingHeader("Controls", ImGuiTreeNodeFlags_DefaultOpen)) {
        ImGui::Checkbox("Play", &state->playing);

        // Every slider commits through a clamped, finite local copy so a NaN
        // typed via Ctrl+click (which AlwaysClamp does not reject) can never
        // reach state -- a NaN playbackSpeed permanently poisons state.time
        // and every downstream spline/solver evaluation, and a NaN squatDepth
        // would poison all 60 keyframes on the next regeneration.
        auto playbackSpeed = state->playbackSpeed;
        ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x * 0.6f);
        if (ImGui::SliderFloat(
                "Playback Speed",
                &playbackSpeed,
                0.1f,
                2.0f,
                "%.2f",
                ImGuiSliderFlags_AlwaysClamp)
            && std::isfinite(playbackSpeed))
          state->playbackSpeed = std::clamp(playbackSpeed, 0.1f, 2.0f);

        auto squatDepth = state->squatDepth;
        ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x * 0.6f);
        if (ImGui::SliderFloat(
                "Squat Depth (m)",
                &squatDepth,
                0.0f,
                0.25f,
                "%.3f",
                ImGuiSliderFlags_AlwaysClamp)
            && std::isfinite(squatDepth))
          state->squatDepth = std::clamp(squatDepth, 0.0f, 0.25f);
        // Regenerate on drag release (IsItemDeactivatedAfterEdit alone -- the
        // slider does not report a value change on the release frame, so an
        // additional edited-this-frame conjunct would make mouse drags a
        // no-op), deferred to the next frame via regenerateRequested.
        if (ImGui::IsItemDeactivatedAfterEdit())
          state->regenerateRequested = true;
        if (ImGui::Button("Regenerate Keyframes"))
          state->regenerateRequested = true;

        auto frictionCoeff = state->frictionCoeff;
        ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x * 0.6f);
        if (ImGui::SliderFloat(
                "Friction Coefficient",
                &frictionCoeff,
                0.0f,
                1.5f,
                "%.2f",
                ImGuiSliderFlags_AlwaysClamp)
            && std::isfinite(frictionCoeff))
          state->frictionCoeff = std::clamp(frictionCoeff, 0.0f, 1.5f);

        auto forceScale = state->forceScale;
        ImGui::SetNextItemWidth(ImGui::GetContentRegionAvail().x * 0.6f);
        if (ImGui::SliderFloat(
                "Force Arrow Scale",
                &forceScale,
                0.0001f,
                0.01f,
                "%.4f",
                ImGuiSliderFlags_AlwaysClamp)
            && std::isfinite(forceScale))
          state->forceScale = std::clamp(forceScale, 0.0001f, 0.01f);

        const Eigen::Vector3d gravity = state->world->getGravity();
        ImGui::Text(
            "Gravity: (%.2f, %.2f, %.2f)", gravity[0], gravity[1], gravity[2]);
      }

      if (ImGui::CollapsingHeader("Status", ImGuiTreeNodeFlags_DefaultOpen)) {
        if (state->feasible)
          ImGui::TextColored(ImVec4(0.0f, 1.0f, 0.0f, 1.0f), "FEASIBLE");
        else
          ImGui::TextColored(ImVec4(1.0f, 0.0f, 0.0f, 1.0f), "INFEASIBLE");

        ImGui::Text("Residual Norm: %.4f", state->residualNorm);

        const double bodyMass = state->biped->getMass();
        const double bodyWeight = bodyMass * state->world->getGravity().norm();
        ImGui::Text("Total Vertical Force: %.2f N", state->totalVerticalForce);
        ImGui::Text("Body Weight: %.2f N", bodyWeight);
        ImGui::Text(
            "Ratio: %.2f",
            bodyWeight > 1e-6 ? state->totalVerticalForce / bodyWeight : 0.0);

        ImGui::Separator();
        ImGui::Text("Contact Forces:");
        for (std::size_t i = 0; i < state->contactForces.size(); ++i)
          ImGui::Text(
              "  Contact %zu: %.2f N", i, state->contactForces[i].norm());
      }

      if (ImGui::CollapsingHeader("Plots", ImGuiTreeNodeFlags_DefaultOpen)) {
        for (std::size_t i = 0; i < state->torqueNames.size(); ++i) {
          ImGui::PlotLines(
              state->torqueNames[i].c_str(),
              state->torquePlots[i].data(),
              static_cast<int>(state->torquePlots[i].size()),
              0,
              nullptr,
              -200.0f,
              200.0f,
              ImVec2(0, ImGui::GetFontSize() * 5.0f));
        }
        ImGui::PlotLines(
            "Total Vertical GRF (N)",
            state->plotSamples.data(),
            static_cast<int>(state->plotSamples.size()),
            0,
            nullptr,
            0.0f,
            1000.0f,
            ImVec2(0, ImGui::GetFontSize() * 5.0f));
      }
    };

    return setup;
  };

  return scene;
}

} // namespace dart_demos
