/*
 * Copyright (c) 2011, The DART development contributors
 * All rights reserved.
 *
 * The list of contributors can be found at:
 *   https://github.com/dartsim/dart/blob/main/LICENSE
 *
 * This file is provided under the following "BSD-style" License:
 *   Redistribution and use in source and binary forms, with or
 *   without modification, are permitted provided that the following
 *   conditions are met:
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
 *   CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 *   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 *   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *   DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 *   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 *   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 *   AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *   LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *   ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *   POSSIBILITY OF SUCH DAMAGE.
 */

#include <dart/simulation/experimental/comps/joint.hpp>
#include <dart/simulation/experimental/multi_body/link.hpp>
#include <dart/simulation/experimental/multi_body/multi_body.hpp>
#include <dart/simulation/experimental/world.hpp>

#include <gtest/gtest.h>

namespace dse = dart::simulation::experimental;

//==============================================================================
// Link Handle Basic Tests
//==============================================================================

TEST(Link, GetName)
{
  dse::World world;
  auto robot = world.addMultiBody("robot");
  auto base = robot.addLink("base_link");

  EXPECT_EQ(base.getName(), "base_link");
}

TEST(Link, AutoGeneratedName)
{
  dse::World world;
  auto robot = world.addMultiBody("robot");

  auto link1 = robot.addLink("");
  auto link2 = robot.addLink("");

  EXPECT_EQ(link1.getName(), "link_001");
  EXPECT_EQ(link2.getName(), "link_002");
}

TEST(Link, CustomNames)
{
  dse::World world;
  auto robot = world.addMultiBody("robot");

  auto shoulder = robot.addLink("shoulder_link");
  auto elbow = robot.addLink("elbow_link");
  auto wrist = robot.addLink("wrist_link");

  EXPECT_EQ(shoulder.getName(), "shoulder_link");
  EXPECT_EQ(elbow.getName(), "elbow_link");
  EXPECT_EQ(wrist.getName(), "wrist_link");
}

//==============================================================================
// Link Parent Joint Tests
//==============================================================================

TEST(Link, RootLinkHasInvalidParentJoint)
{
  dse::World world;
  auto robot = world.addMultiBody("robot");
  auto base = robot.addLink("base");

  auto parentJoint = base.getParentJoint();
  EXPECT_FALSE(parentJoint.isValid());
}

TEST(Link, NonRootLinkHasValidParentJoint)
{
  dse::World world;
  auto robot = world.addMultiBody("robot");
  auto base = robot.addLink("base");
  auto link1
      = robot.addLink("link1", {.parentLink = base, .jointName = "joint1"});

  auto parentJoint = link1.getParentJoint();
  EXPECT_TRUE(parentJoint.isValid());
  EXPECT_EQ(parentJoint.getName(), "joint1");
}

TEST(Link, GetParentJointType)
{
  dse::World world;
  auto robot = world.addMultiBody("robot");
  auto base = robot.addLink("base");
  auto link1 = robot.addLink(
      "link1",
      {.parentLink = base,
       .jointName = "revolute_joint",
       .jointType = dse::comps::JointType::Revolute});
  auto link2 = robot.addLink(
      "link2",
      {.parentLink = link1,
       .jointName = "prismatic_joint",
       .jointType = dse::comps::JointType::Prismatic});

  EXPECT_EQ(link1.getParentJoint().getType(), dse::comps::JointType::Revolute);
  EXPECT_EQ(link2.getParentJoint().getType(), dse::comps::JointType::Prismatic);
}

//==============================================================================
// Link Frame Interface Tests
//==============================================================================

TEST(Link, InheritsFromFrame)
{
  dse::World world;
  auto robot = world.addMultiBody("robot");
  auto base = robot.addLink("base");

  EXPECT_TRUE(base.isValid());
  EXPECT_TRUE(base.getEntity() != entt::null);
  EXPECT_EQ(base.getWorld(), &world);
}

TEST(Link, GetLocalTransformIdentityByDefault)
{
  dse::World world;
  auto robot = world.addMultiBody("robot");
  auto base = robot.addLink("base");

  const auto& localTf = base.getLocalTransform();
  EXPECT_TRUE(
      localTf.matrix().isApprox(Eigen::Isometry3d::Identity().matrix()));
}

TEST(Link, GetWorldTransformAfterSimulationMode)
{
  dse::World world;
  auto robot = world.addMultiBody("robot");
  auto base = robot.addLink("base");
  auto link1
      = robot.addLink("link1", {.parentLink = base, .jointName = "joint1"});

  world.enterSimulationMode();
  world.updateKinematics();

  const auto& worldTf = link1.getWorldTransform();
  EXPECT_TRUE(
      worldTf.matrix().isApprox(Eigen::Isometry3d::Identity().matrix()));
}

//==============================================================================
// Link Handle Copy Semantics
//==============================================================================

TEST(Link, HandleCopySemantics)
{
  dse::World world;
  auto robot = world.addMultiBody("robot");
  auto link1 = robot.addLink("link1");

  auto link2 = link1;

  EXPECT_EQ(link1.getEntity(), link2.getEntity());
  EXPECT_EQ(link1.getName(), link2.getName());
}

TEST(Link, HandleFromDifferentPaths)
{
  dse::World world;
  auto robot = world.addMultiBody("robot");
  auto base = robot.addLink("base");
  auto link1
      = robot.addLink("link1", {.parentLink = base, .jointName = "joint1"});

  auto joint = link1.getParentJoint();
  auto linkViaJoint = joint.getChildLink();

  EXPECT_EQ(link1.getEntity(), linkViaJoint.getEntity());
  EXPECT_EQ(link1.getName(), linkViaJoint.getName());
}

TEST(Link, GetLinkViaMultiBody)
{
  dse::World world;
  auto robot = world.addMultiBody("robot");
  auto base = robot.addLink("base");
  robot.addLink("link1", {.parentLink = base, .jointName = "joint1"});

  auto foundLink = robot.getLink("link1");
  ASSERT_TRUE(foundLink.has_value());
  EXPECT_EQ(foundLink->getName(), "link1");
}

//==============================================================================
// Link Chain Tests
//==============================================================================

TEST(Link, MultipleLinkChain)
{
  dse::World world;
  auto robot = world.addMultiBody("robot");

  auto base = robot.addLink("base");
  auto link1
      = robot.addLink("link1", {.parentLink = base, .jointName = "joint1"});
  auto link2
      = robot.addLink("link2", {.parentLink = link1, .jointName = "joint2"});
  auto link3
      = robot.addLink("link3", {.parentLink = link2, .jointName = "joint3"});

  EXPECT_EQ(robot.getLinkCount(), 4u);

  EXPECT_FALSE(base.getParentJoint().isValid());
  EXPECT_TRUE(link1.getParentJoint().isValid());
  EXPECT_TRUE(link2.getParentJoint().isValid());
  EXPECT_TRUE(link3.getParentJoint().isValid());

  EXPECT_EQ(link1.getParentJoint().getParentLink().getName(), "base");
  EXPECT_EQ(link2.getParentJoint().getParentLink().getName(), "link1");
  EXPECT_EQ(link3.getParentJoint().getParentLink().getName(), "link2");
}

TEST(Link, BranchingTree)
{
  dse::World world;
  auto robot = world.addMultiBody("humanoid");

  auto torso = robot.addLink("torso");
  auto leftArm
      = robot.addLink("left_arm", {.parentLink = torso, .jointName = "l_sho"});
  auto rightArm
      = robot.addLink("right_arm", {.parentLink = torso, .jointName = "r_sho"});
  auto head = robot.addLink("head", {.parentLink = torso, .jointName = "neck"});

  EXPECT_EQ(robot.getLinkCount(), 4u);
  EXPECT_EQ(robot.getJointCount(), 3u);

  EXPECT_EQ(leftArm.getParentJoint().getParentLink().getName(), "torso");
  EXPECT_EQ(rightArm.getParentJoint().getParentLink().getName(), "torso");
  EXPECT_EQ(head.getParentJoint().getParentLink().getName(), "torso");
}

//==============================================================================
// Forward Kinematics Integration Tests
//==============================================================================

TEST(Link, LocalTransformFromJointPosition)
{
  dse::World world;
  auto robot = world.addMultiBody("arm");

  auto base = robot.addLink("base");
  auto link1 = robot.addLink(
      "link1",
      {.parentLink = base,
       .jointName = "joint1",
       .jointType = dse::comps::JointType::Revolute,
       .jointAxis = Eigen::Vector3d::UnitZ()});

  link1.getParentJoint().setPosition(Eigen::VectorXd::Zero(1));

  const auto& localTf = link1.getLocalTransform();
  EXPECT_TRUE(localTf.isApprox(Eigen::Isometry3d::Identity()));
}

TEST(Link, LocalTransformRotatesWithJoint)
{
  dse::World world;
  auto robot = world.addMultiBody("arm");

  auto base = robot.addLink("base");
  auto link1 = robot.addLink(
      "link1",
      {.parentLink = base,
       .jointName = "joint1",
       .jointType = dse::comps::JointType::Revolute,
       .jointAxis = Eigen::Vector3d::UnitZ()});

  Eigen::VectorXd pos(1);
  pos << M_PI / 2;
  link1.getParentJoint().setPosition(pos);

  const auto& localTf = link1.getLocalTransform();

  Eigen::Vector3d rotatedX = localTf.rotation() * Eigen::Vector3d::UnitX();
  EXPECT_TRUE(rotatedX.isApprox(Eigen::Vector3d::UnitY(), 1e-10));
}

TEST(Link, LocalTransformCacheInvalidatedOnJointChange)
{
  dse::World world;
  auto robot = world.addMultiBody("arm");

  auto base = robot.addLink("base");
  auto link1 = robot.addLink(
      "link1",
      {.parentLink = base,
       .jointName = "joint1",
       .jointType = dse::comps::JointType::Revolute,
       .jointAxis = Eigen::Vector3d::UnitZ()});

  link1.getParentJoint().setPosition(Eigen::VectorXd::Zero(1));
  const auto& tf1 = link1.getLocalTransform();
  EXPECT_TRUE(tf1.isApprox(Eigen::Isometry3d::Identity()));

  Eigen::VectorXd pos(1);
  pos << M_PI;
  link1.getParentJoint().setPosition(pos);

  const auto& tf2 = link1.getLocalTransform();
  Eigen::Vector3d rotatedX = tf2.rotation() * Eigen::Vector3d::UnitX();
  EXPECT_TRUE(rotatedX.isApprox(-Eigen::Vector3d::UnitX(), 1e-10));
}

TEST(Link, PrismaticJointTranslatesLink)
{
  dse::World world;
  auto robot = world.addMultiBody("slider");

  auto base = robot.addLink("base");
  auto link1 = robot.addLink(
      "link1",
      {.parentLink = base,
       .jointName = "joint1",
       .jointType = dse::comps::JointType::Prismatic,
       .jointAxis = Eigen::Vector3d::UnitX()});

  Eigen::VectorXd pos(1);
  pos << 1.5;
  link1.getParentJoint().setPosition(pos);

  const auto& localTf = link1.getLocalTransform();
  EXPECT_TRUE(
      localTf.translation().isApprox(Eigen::Vector3d(1.5, 0, 0), 1e-10));
  EXPECT_TRUE(localTf.rotation().isApprox(Eigen::Matrix3d::Identity()));
}

TEST(Link, TwoLinkArmForwardKinematics)
{
  dse::World world;
  auto robot = world.addMultiBody("arm");

  auto base = robot.addLink("base");
  auto link1 = robot.addLink(
      "link1",
      {.parentLink = base,
       .jointName = "joint1",
       .jointType = dse::comps::JointType::Revolute,
       .jointAxis = Eigen::Vector3d::UnitZ()});
  auto link2 = robot.addLink(
      "link2",
      {.parentLink = link1,
       .jointName = "joint2",
       .jointType = dse::comps::JointType::Revolute,
       .jointAxis = Eigen::Vector3d::UnitZ()});

  Eigen::VectorXd pos1(1), pos2(1);
  pos1 << M_PI / 4;
  pos2 << -M_PI / 4;

  link1.getParentJoint().setPosition(pos1);
  link2.getParentJoint().setPosition(pos2);

  world.enterSimulationMode();
  world.updateKinematics();

  const auto& worldTf2 = link2.getWorldTransform();

  EXPECT_TRUE(worldTf2.rotation().isApprox(Eigen::Matrix3d::Identity(), 1e-10));
}
