# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: CI Downstream

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - ".github/workflows/cache_*.yml"
      - "docker/dev/**"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - ".github/workflows/cache_*.yml"
      - "docker/dev/**"
  schedule:
    # Cron syntax: [minute hour day_of_the_month month day_of_the_week]
    - cron: "0 2 * * 0,3" # Run every Sunday and Wednesday at 02:00
  workflow_dispatch:

env:
  DOCKER_REPO: jslee02/dart-dev # https://hub.docker.com/repository/docker/jslee02/dart-dev

jobs:
  tracy:
    name: gazebo
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dart_version: [v6.14]
        build_min: [ON]
    env:
      OS_VERSION: gazebo
      DART_VERSION: ${{ matrix.dart_version }}
    steps:
      # https://github.com/marketplace/actions/docker-setup-qemu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # https://github.com/marketplace/actions/docker-login
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          file: ./docker/dev/${{ env.DART_VERSION }}/Dockerfile.${{ env.OS_VERSION }}
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ env.OS_VERSION }}-${{ env.DART_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
